/*
 * clsic-codec.c -- ALSA SoC Audio driver for CLSIC codec
 *
 * Copyright (C) 2015-2018 Cirrus Logic, Inc. and
 *			   Cirrus Logic International Semiconductor Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include <linux/module.h>
#include <linux/moduleparam.h>
#include <linux/init.h>
#include <linux/delay.h>
#include <linux/pm.h>
#include <linux/pm_runtime.h>

#include <sound/core.h>
#include <sound/compress_driver.h>
#include <sound/pcm.h>
#include <sound/pcm_params.h>
#include <sound/soc.h>
#include <sound/tlv.h>

#include <linux/mfd/tacna/core.h>
#include <linux/mfd/tacna/registers.h>

#include "tacna.h"

#include <linux/mfd/clsic/core.h>
#include <linux/mfd/clsic/rassrv.h>

#define CLSIC_N_FLL			2
#define CLSIC_NUM_DSP			2
#define CLSIC_DSP1_N_RX_CHANNELS	9
#define CLSIC_DSP1_N_TX_CHANNELS	9
#define CLSIC_DSP2_N_RX_CHANNELS	8
#define CLSIC_DSP2_N_TX_CHANNELS	8

/* CLSIC codecs have four micbias switches named MICBIAS1A to MICBIAS1D */
#define CLSIC_MICBIAS_COUNT	4
#define CLSIC_MICBIAS_NAME_MAX	10

struct clsic_codec {
	struct tacna_priv core;
	struct tacna_fll fll[3];
	struct clsic *clsic;
	struct snd_soc_codec *codec;
	bool host_controls_dsp2;
	bool micbias_active_discharge[CLSIC_MICBIAS_COUNT];
};

static const struct wm_adsp_region clsic_dsp2_regions[] = {
	{ .type = WMFW_HALO_PM_PACKED, .base = 0x5800000 },
	{ .type = WMFW_HALO_XM_PACKED, .base = 0x4000000 },
	{ .type = WMFW_ADSP2_XM, .base = 0x4800000 },
	{ .type = WMFW_HALO_YM_PACKED, .base = 0x4C00000 },
	{ .type = WMFW_ADSP2_YM, .base = 0x5400000 },
};

static const unsigned int clsic_dsp2_sram_power_regs[] = {
	CLSIC_DSP2_XM_SRAM_IBUS_PSD_1,
	CLSIC_DSP2_XM_SRAM_IBUS_RET_1,
	CLSIC_DSP2_XM_SRAM_IBUS_NAP_1,
	CLSIC_DSP2_YM_SRAM_IBUS_PSD_1,
	CLSIC_DSP2_YM_SRAM_IBUS_RET_1,
	CLSIC_DSP2_YM_SRAM_IBUS_NAP_1,
	CLSIC_DSP2_PM_SRAM_IBUS_PSD_1,
	CLSIC_DSP2_PM_SRAM_IBUS_RET_1,
	CLSIC_DSP2_PM_SRAM_IBUS_NAP_1,
	0, /* end of list */
};

#define TACNA_DSP_CLOCK_FREQ_OFFS		0x00000
#define TACNA_DSP_CLOCK_STATUS_OFFS		0x00008

static int clsic_dsp_memory_enable(struct tacna_priv *priv)
{
	struct regmap *regmap = priv->tacna->regmap;
	const unsigned int *reg_list = clsic_dsp2_sram_power_regs;
	int ret;

	for (; *reg_list != 0; ++reg_list) {
		ret = regmap_write(regmap, *reg_list, 0);
		if (ret)
			goto err;

		udelay(1); /* allow bank to power-up */
	}

	return 0;
err:
	dev_err(priv->dev, "Failed to write SRAM enable 0x%x (%d)\n",
		*reg_list, ret);

	return ret;
}

static void clsic_dsp_memory_disable(struct tacna_priv *priv)
{
	struct regmap *regmap = priv->tacna->regmap;
	const unsigned int *reg_list = clsic_dsp2_sram_power_regs;
	int ret;

	for (; *reg_list != 0; ++reg_list) {
		ret = regmap_update_bits(regmap, *reg_list, 0x1f, 0x1f);
		if (ret)
			dev_warn(priv->dev,
				 "Failed to write SRAM disable 0x%x (%d)\n",
				 *reg_list, ret);
	}
}

static int clsic_dsp_power_ev(struct snd_soc_dapm_widget *w,
			      struct snd_kcontrol *kcontrol, int event)
{
	struct snd_soc_codec *codec = snd_soc_dapm_to_codec(w->dapm);
	struct tacna_priv *priv = snd_soc_codec_get_drvdata(codec);
	struct tacna *tacna = priv->tacna;
	struct wm_adsp *dsps = snd_soc_codec_get_drvdata(codec);
	struct wm_adsp *dsp = &dsps[w->shift];
	unsigned int freq;
	int ret;

	switch (event) {
	case SND_SOC_DAPM_PRE_PMU:
		/* write to DSP2_PWR_CTRL to enable core */
		ret = regmap_write(dsp->regmap, CLSIC_DSP2_PWR_CTRL,
				   CLSIC_DSP2_RST_N);
		if (ret) {
			dev_err(codec->dev, "Failed to enable DSP2: %d\n", ret);
			return ret;
		}

		ret = regmap_read(tacna->regmap, TACNA_DSP_CLOCK3, &freq);
		if (ret) {
			dev_err(codec->dev,
				"Failed to read TACNA_DSP_CLOCK3: %d\n", ret);
			goto error;
		}

		ret = regmap_write(dsp->regmap,
				   dsp->base + TACNA_DSP_CLOCK_FREQ_OFFS,
				   freq);
		if (ret) {
			dev_err(codec->dev,
				"Failed to set HALO clock freq: %d\n", ret);
			goto error;
		}

		ret = clsic_dsp_memory_enable(priv);
		if (ret)
			goto error;

		return wm_halo_early_event(w, kcontrol, event);
	case SND_SOC_DAPM_PRE_PMD:
		ret = wm_halo_early_event(w, kcontrol, event);
		clsic_dsp_memory_disable(priv);
		return ret;
	default:
		return 0;
	}

error:
	regmap_write(dsp->regmap, CLSIC_DSP2_PWR_CTRL,
		     CLSIC_DSP2_ISOLATE_ENABLE | CLSIC_DSP2_SHUTOFF);
	return ret;
}

/*
 * Populate the micbias_active_discharge array with the values from the
 * devicetree and appropriately set the discharge bits in the regmap cache.
 */
static void clsic_micbias_init(struct clsic_codec *clsic_codec)
{
	int i, rad, val, shift;
	char name[CLSIC_MICBIAS_NAME_MAX];
	struct device_node *np;

	for (i = 0; i < CLSIC_MICBIAS_COUNT; ++i) {
		snprintf(name, sizeof(name), "MICBIAS1%c", 'A' + i);

		np = of_get_child_by_name(clsic_codec->clsic->dev->of_node,
					  name);
		if (!np)
			continue;

		of_property_read_u32(np, "regulator-active-discharge", &rad);
		clsic_codec->micbias_active_discharge[i] = (rad > 0);

		/*
		 * When this function is called the device is not powered up so
		 * perform the same action as the PRE_PMD event.
		 *
		 * The shift will be 0, 4, 8 or 12 as the zero indexed loop
		 * steps through the four micbiases.
		 */
		shift = TACNA_MICB1B_EN_SHIFT * i;
		if (clsic_codec->micbias_active_discharge[i])
			val = TACNA_MICB1A_DISCH;
		else
			val = 0;

		regmap_update_bits(clsic_codec->core.tacna->regmap,
				   TACNA_MICBIAS_CTRL5,
				   (TACNA_MICB1A_EN_MASK |
				    TACNA_MICB1A_DISCH_MASK) << shift,
				   val << shift);
	}
}

/*
 * It is recommended to set _DISCH when clearing _EN and recommended to clear
 * _DISCH when setting _EN - use regmap_update_bits to make sure that at most
 * only one of the bits can be set at any point in time.
 */
int clsic_micbias_ev(struct snd_soc_dapm_widget *w,
		     struct snd_kcontrol *kcontrol, int event)
{
	struct snd_soc_codec *codec = snd_soc_dapm_to_codec(w->dapm);
	struct clsic_codec *clsic_codec = snd_soc_codec_get_drvdata(codec);
	int val = 0;
	int ret;

	switch (event) {
	case SND_SOC_DAPM_PRE_PMU:
		val = TACNA_MICB1A_EN;
		break;
	case SND_SOC_DAPM_PRE_PMD:
		if (clsic_codec->micbias_active_discharge[w->shift >> 2])
			val = TACNA_MICB1A_DISCH;
		break;
	default:
		return 0;
	}

	ret = regmap_update_bits(clsic_codec->core.tacna->regmap,
				 TACNA_MICBIAS_CTRL5,
				 (TACNA_MICB1A_EN_MASK |
				  TACNA_MICB1A_DISCH_MASK) << w->shift,
				 val << w->shift);

	return ret;
}


static const struct snd_kcontrol_new clsic_snd_controls[] = {
SOC_ENUM("IN1 OSR", tacna_in_dmic_osr[0]),
SOC_ENUM("IN2 OSR", tacna_in_dmic_osr[1]),
SOC_ENUM("IN3 OSR", tacna_in_dmic_osr[2]),
SOC_ENUM("IN4 OSR", tacna_in_dmic_osr[3]),

SOC_ENUM("IN HPF Cutoff Frequency", tacna_in_hpf_cut_enum),

SOC_SINGLE("IN1L HPF Switch", TACNA_IN1L_CONTROL1, TACNA_IN1L_HPF_SHIFT, 1, 0),
SOC_SINGLE("IN1R HPF Switch", TACNA_IN1R_CONTROL1, TACNA_IN1R_HPF_SHIFT, 1, 0),
SOC_SINGLE("IN2L HPF Switch", TACNA_IN2L_CONTROL1, TACNA_IN2L_HPF_SHIFT, 1, 0),
SOC_SINGLE("IN2R HPF Switch", TACNA_IN2R_CONTROL1, TACNA_IN2R_HPF_SHIFT, 1, 0),
SOC_SINGLE("IN3L HPF Switch", TACNA_IN3L_CONTROL1, TACNA_IN3L_HPF_SHIFT, 1, 0),
SOC_SINGLE("IN3R HPF Switch", TACNA_IN3R_CONTROL1, TACNA_IN3R_HPF_SHIFT, 1, 0),
SOC_SINGLE("IN4L HPF Switch", TACNA_IN4L_CONTROL1, TACNA_IN4L_HPF_SHIFT, 1, 0),
SOC_SINGLE("IN4R HPF Switch", TACNA_IN4R_CONTROL1, TACNA_IN4R_HPF_SHIFT, 1, 0),

SOC_SINGLE_TLV("IN1L Digital Volume", TACNA_IN1L_CONTROL2,
	       TACNA_IN1L_VOL_SHIFT, 0xbf, 0, tacna_digital_tlv),
SOC_SINGLE_TLV("IN1R Digital Volume", TACNA_IN1R_CONTROL2,
	       TACNA_IN1R_VOL_SHIFT, 0xbf, 0, tacna_digital_tlv),
SOC_SINGLE_TLV("IN2L Digital Volume", TACNA_IN2L_CONTROL2,
	       TACNA_IN2L_VOL_SHIFT, 0xbf, 0, tacna_digital_tlv),
SOC_SINGLE_TLV("IN2R Digital Volume", TACNA_IN2R_CONTROL2,
	       TACNA_IN2R_VOL_SHIFT, 0xbf, 0, tacna_digital_tlv),
SOC_SINGLE_TLV("IN3L Digital Volume", TACNA_IN3L_CONTROL2,
	       TACNA_IN3L_VOL_SHIFT, 0xbf, 0, tacna_digital_tlv),
SOC_SINGLE_TLV("IN3R Digital Volume", TACNA_IN3R_CONTROL2,
	       TACNA_IN3R_VOL_SHIFT, 0xbf, 0, tacna_digital_tlv),
SOC_SINGLE_TLV("IN4L Digital Volume", TACNA_IN4L_CONTROL2,
	       TACNA_IN4L_VOL_SHIFT, 0xbf, 0, tacna_digital_tlv),
SOC_SINGLE_TLV("IN4R Digital Volume", TACNA_IN4R_CONTROL2,
	       TACNA_IN4R_VOL_SHIFT, 0xbf, 0, tacna_digital_tlv),

SOC_ENUM("Input Ramp Up", tacna_in_vi_ramp),
SOC_ENUM("Input Ramp Down", tacna_in_vd_ramp),

TACNA_MIXER_CONTROLS("EQ1", TACNA_EQ1_INPUT1),
TACNA_MIXER_CONTROLS("EQ2", TACNA_EQ2_INPUT1),
TACNA_MIXER_CONTROLS("EQ3", TACNA_EQ3_INPUT1),
TACNA_MIXER_CONTROLS("EQ4", TACNA_EQ4_INPUT1),

SOC_ENUM_EXT("EQ1 Mode", tacna_eq_mode[0], tacna_eq_mode_get,
	     tacna_eq_mode_put),
TACNA_EQ_COEFF_CONTROLS(EQ1),
SOC_SINGLE_TLV("EQ1 B1 Volume", TACNA_EQ1_GAIN1, TACNA_EQ1_B1_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ1 B2 Volume", TACNA_EQ1_GAIN1, TACNA_EQ1_B2_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ1 B3 Volume", TACNA_EQ1_GAIN1, TACNA_EQ1_B3_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ1 B4 Volume", TACNA_EQ1_GAIN1, TACNA_EQ1_B4_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ1 B5 Volume", TACNA_EQ1_GAIN2, TACNA_EQ1_B5_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),

SOC_ENUM_EXT("EQ2 Mode", tacna_eq_mode[1], tacna_eq_mode_get,
	     tacna_eq_mode_put),
TACNA_EQ_COEFF_CONTROLS(EQ2),
SOC_SINGLE_TLV("EQ2 B1 Volume", TACNA_EQ2_GAIN1, TACNA_EQ2_B1_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ2 B2 Volume", TACNA_EQ2_GAIN1, TACNA_EQ2_B2_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ2 B3 Volume", TACNA_EQ2_GAIN1, TACNA_EQ2_B3_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ2 B4 Volume", TACNA_EQ2_GAIN1, TACNA_EQ2_B4_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ2 B5 Volume", TACNA_EQ2_GAIN2, TACNA_EQ2_B5_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),

SOC_ENUM_EXT("EQ3 Mode", tacna_eq_mode[2], tacna_eq_mode_get,
	     tacna_eq_mode_put),
TACNA_EQ_COEFF_CONTROLS(EQ3),
SOC_SINGLE_TLV("EQ3 B1 Volume", TACNA_EQ3_GAIN1, TACNA_EQ3_B1_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ3 B2 Volume", TACNA_EQ3_GAIN1, TACNA_EQ3_B2_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ3 B3 Volume", TACNA_EQ3_GAIN1, TACNA_EQ3_B3_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ3 B4 Volume", TACNA_EQ3_GAIN1, TACNA_EQ3_B4_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ3 B5 Volume", TACNA_EQ3_GAIN2, TACNA_EQ3_B5_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),

SOC_ENUM_EXT("EQ4 Mode", tacna_eq_mode[3], tacna_eq_mode_get,
	     tacna_eq_mode_put),
TACNA_EQ_COEFF_CONTROLS(EQ4),
SOC_SINGLE_TLV("EQ4 B1 Volume", TACNA_EQ4_GAIN1, TACNA_EQ4_B1_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ4 B2 Volume", TACNA_EQ4_GAIN1, TACNA_EQ4_B2_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ4 B3 Volume", TACNA_EQ4_GAIN1, TACNA_EQ4_B3_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ4 B4 Volume", TACNA_EQ4_GAIN1, TACNA_EQ4_B4_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),
SOC_SINGLE_TLV("EQ4 B5 Volume", TACNA_EQ4_GAIN2, TACNA_EQ4_B5_GAIN_SHIFT,
	       24, 0, tacna_eq_tlv),

TACNA_MIXER_CONTROLS("DRC1L", TACNA_DRC1L_INPUT1),
TACNA_MIXER_CONTROLS("DRC1R", TACNA_DRC1R_INPUT1),
TACNA_MIXER_CONTROLS("DRC2L", TACNA_DRC2L_INPUT1),
TACNA_MIXER_CONTROLS("DRC2R", TACNA_DRC2R_INPUT1),

SND_SOC_BYTES_MASK("DRC1 Coefficients", TACNA_DRC1_CONTROL1, 4,
		   TACNA_DRC1R_EN | TACNA_DRC1L_EN),
SND_SOC_BYTES_MASK("DRC2 Coefficients", TACNA_DRC2_CONTROL1, 4,
		   TACNA_DRC2R_EN | TACNA_DRC2L_EN),

TACNA_MIXER_CONTROLS("LHPF1", TACNA_LHPF1_INPUT1),
TACNA_MIXER_CONTROLS("LHPF2", TACNA_LHPF2_INPUT1),
TACNA_MIXER_CONTROLS("LHPF3", TACNA_LHPF3_INPUT1),
TACNA_MIXER_CONTROLS("LHPF4", TACNA_LHPF4_INPUT1),

TACNA_LHPF_CONTROL("LHPF1 Coefficients", TACNA_LHPF1_COEFF),
TACNA_LHPF_CONTROL("LHPF2 Coefficients", TACNA_LHPF2_COEFF),
TACNA_LHPF_CONTROL("LHPF3 Coefficients", TACNA_LHPF3_COEFF),
TACNA_LHPF_CONTROL("LHPF4 Coefficients", TACNA_LHPF4_COEFF),

SOC_ENUM("LHPF1 Mode", tacna_lhpf1_mode),
SOC_ENUM("LHPF2 Mode", tacna_lhpf2_mode),
SOC_ENUM("LHPF3 Mode", tacna_lhpf3_mode),
SOC_ENUM("LHPF4 Mode", tacna_lhpf4_mode),

TACNA_RATE_CONTROL("Sample Rate 1", 1),
TACNA_RATE_CONTROL("Sample Rate 2", 2),
TACNA_RATE_CONTROL("Sample Rate 3", 3),
TACNA_ASYNC_RATE_CONTROL("Async Sample Rate 1", 1),
TACNA_ASYNC_RATE_CONTROL("Async Sample Rate 2", 2),

TACNA_RATE_ENUM("FX Rate", tacna_fx_rate),

TACNA_RATE_ENUM("ISRC1 FSL", tacna_isrc_fsl[0]),
TACNA_RATE_ENUM("ISRC1 FSH", tacna_isrc_fsh[0]),

TACNA_RATE_ENUM("ASRC1 Rate 1", tacna_asrc1_rate[0]),
TACNA_RATE_ENUM("ASRC1 Rate 2", tacna_asrc1_rate[1]),

TACNA_RATE_ENUM("ASRC2 Rate 1", tacna_asrc2_rate[0]),
TACNA_RATE_ENUM("ASRC2 Rate 2", tacna_asrc2_rate[1]),

SOC_ENUM_EXT("IN1L Rate", tacna_input_rate[0],
	     snd_soc_get_enum_double, tacna_in_rate_put),
SOC_ENUM_EXT("IN1R Rate", tacna_input_rate[1],
	     snd_soc_get_enum_double, tacna_in_rate_put),
SOC_ENUM_EXT("IN2L Rate", tacna_input_rate[2],
	     snd_soc_get_enum_double, tacna_in_rate_put),
SOC_ENUM_EXT("IN2R Rate", tacna_input_rate[3],
	     snd_soc_get_enum_double, tacna_in_rate_put),
SOC_ENUM_EXT("IN3L Rate", tacna_input_rate[4],
	     snd_soc_get_enum_double, tacna_in_rate_put),
SOC_ENUM_EXT("IN3R Rate", tacna_input_rate[5],
	     snd_soc_get_enum_double, tacna_in_rate_put),
SOC_ENUM_EXT("IN4L Rate", tacna_input_rate[6],
	     snd_soc_get_enum_double, tacna_in_rate_put),
SOC_ENUM_EXT("IN4R Rate", tacna_input_rate[7],
	     snd_soc_get_enum_double, tacna_in_rate_put),

TACNA_MIXER_CONTROLS("ASP1TX1", TACNA_ASP1TX1_INPUT1),
TACNA_MIXER_CONTROLS("ASP1TX2", TACNA_ASP1TX2_INPUT1),
TACNA_MIXER_CONTROLS("ASP1TX3", TACNA_ASP1TX3_INPUT1),
TACNA_MIXER_CONTROLS("ASP1TX4", TACNA_ASP1TX4_INPUT1),
TACNA_MIXER_CONTROLS("ASP1TX5", TACNA_ASP1TX5_INPUT1),
TACNA_MIXER_CONTROLS("ASP1TX6", TACNA_ASP1TX6_INPUT1),
TACNA_MIXER_CONTROLS("ASP1TX7", TACNA_ASP1TX7_INPUT1),
TACNA_MIXER_CONTROLS("ASP1TX8", TACNA_ASP1TX8_INPUT1),

TACNA_MIXER_CONTROLS("ASP2TX1", TACNA_ASP2TX1_INPUT1),
TACNA_MIXER_CONTROLS("ASP2TX2", TACNA_ASP2TX2_INPUT1),
TACNA_MIXER_CONTROLS("ASP2TX3", TACNA_ASP2TX3_INPUT1),
TACNA_MIXER_CONTROLS("ASP2TX4", TACNA_ASP2TX4_INPUT1),
TACNA_MIXER_CONTROLS("ASP2TX5", TACNA_ASP2TX5_INPUT1),
TACNA_MIXER_CONTROLS("ASP2TX6", TACNA_ASP2TX6_INPUT1),
TACNA_MIXER_CONTROLS("ASP2TX7", TACNA_ASP2TX7_INPUT1),
TACNA_MIXER_CONTROLS("ASP2TX8", TACNA_ASP2TX8_INPUT1),

TACNA_MIXER_CONTROLS("ASP3TX1", TACNA_ASP3TX1_INPUT1),
TACNA_MIXER_CONTROLS("ASP3TX2", TACNA_ASP3TX2_INPUT1),
TACNA_MIXER_CONTROLS("ASP3TX3", TACNA_ASP3TX3_INPUT1),
TACNA_MIXER_CONTROLS("ASP3TX4", TACNA_ASP3TX4_INPUT1),
TACNA_MIXER_CONTROLS("ASP3TX5", TACNA_ASP3TX5_INPUT1),
TACNA_MIXER_CONTROLS("ASP3TX6", TACNA_ASP3TX6_INPUT1),
TACNA_MIXER_CONTROLS("ASP3TX7", TACNA_ASP3TX7_INPUT1),
TACNA_MIXER_CONTROLS("ASP3TX8", TACNA_ASP3TX8_INPUT1),

TACNA_MIXER_CONTROLS("ASP4TX1", TACNA_ASP4TX1_INPUT1),
TACNA_MIXER_CONTROLS("ASP4TX2", TACNA_ASP4TX2_INPUT1),
TACNA_MIXER_CONTROLS("ASP4TX3", TACNA_ASP4TX3_INPUT1),
TACNA_MIXER_CONTROLS("ASP4TX4", TACNA_ASP4TX4_INPUT1),
TACNA_MIXER_CONTROLS("ASP4TX5", TACNA_ASP4TX5_INPUT1),
TACNA_MIXER_CONTROLS("ASP4TX6", TACNA_ASP4TX6_INPUT1),
TACNA_MIXER_CONTROLS("ASP4TX7", TACNA_ASP4TX7_INPUT1),
TACNA_MIXER_CONTROLS("ASP4TX8", TACNA_ASP4TX8_INPUT1),

TACNA_MIXER_CONTROLS("SLIMTX1", TACNA_SLIMTX1_INPUT1),
TACNA_MIXER_CONTROLS("SLIMTX2", TACNA_SLIMTX2_INPUT1),
TACNA_MIXER_CONTROLS("SLIMTX3", TACNA_SLIMTX3_INPUT1),
TACNA_MIXER_CONTROLS("SLIMTX4", TACNA_SLIMTX4_INPUT1),
TACNA_MIXER_CONTROLS("SLIMTX5", TACNA_SLIMTX5_INPUT1),
TACNA_MIXER_CONTROLS("SLIMTX6", TACNA_SLIMTX6_INPUT1),
TACNA_MIXER_CONTROLS("SLIMTX7", TACNA_SLIMTX7_INPUT1),
TACNA_MIXER_CONTROLS("SLIMTX8", TACNA_SLIMTX8_INPUT1),

TACNA_MIXER_CONTROLS("DSP1RX1", TACNA_DSP1RX1_INPUT1),
TACNA_MIXER_CONTROLS("DSP1RX2", TACNA_DSP1RX2_INPUT1),
TACNA_MIXER_CONTROLS("DSP1RX3", TACNA_DSP1RX3_INPUT1),
TACNA_MIXER_CONTROLS("DSP1RX4", TACNA_DSP1RX4_INPUT1),
TACNA_MIXER_CONTROLS("DSP1RX5", TACNA_DSP1RX5_INPUT1),
TACNA_MIXER_CONTROLS("DSP1RX6", TACNA_DSP1RX6_INPUT1),
TACNA_MIXER_CONTROLS("DSP1RX7", TACNA_DSP1RX7_INPUT1),
TACNA_MIXER_CONTROLS("DSP1RX8", TACNA_DSP1RX8_INPUT1),
TACNA_MIXER_CONTROLS("DSP1RX9", TACNA_DSP1RX9_INPUT1),

TACNA_MIXER_CONTROLS("DSP2RX1", TACNA_DSP2RX1_INPUT1),
TACNA_MIXER_CONTROLS("DSP2RX2", TACNA_DSP2RX2_INPUT1),
TACNA_MIXER_CONTROLS("DSP2RX3", TACNA_DSP2RX3_INPUT1),
TACNA_MIXER_CONTROLS("DSP2RX4", TACNA_DSP2RX4_INPUT1),
TACNA_MIXER_CONTROLS("DSP2RX5", TACNA_DSP2RX5_INPUT1),
TACNA_MIXER_CONTROLS("DSP2RX6", TACNA_DSP2RX6_INPUT1),
TACNA_MIXER_CONTROLS("DSP2RX7", TACNA_DSP2RX7_INPUT1),
TACNA_MIXER_CONTROLS("DSP2RX8", TACNA_DSP2RX8_INPUT1),
};

static const struct snd_kcontrol_new clsic_snd_controls_dsp2_visible[] = {
WM_ADSP_FW_CONTROL("DSP2", 1),
WM_ADSP2_PRELOAD_SWITCH("DSP2", 2),
};

TACNA_MIXER_ENUMS(EQ1, TACNA_EQ1_INPUT1);
TACNA_MIXER_ENUMS(EQ2, TACNA_EQ2_INPUT1);
TACNA_MIXER_ENUMS(EQ3, TACNA_EQ3_INPUT1);
TACNA_MIXER_ENUMS(EQ4, TACNA_EQ4_INPUT1);

TACNA_MIXER_ENUMS(DRC1L, TACNA_DRC1L_INPUT1);
TACNA_MIXER_ENUMS(DRC1R, TACNA_DRC1R_INPUT1);
TACNA_MIXER_ENUMS(DRC2L, TACNA_DRC2L_INPUT1);
TACNA_MIXER_ENUMS(DRC2R, TACNA_DRC2R_INPUT1);

TACNA_MIXER_ENUMS(LHPF1, TACNA_LHPF1_INPUT1);
TACNA_MIXER_ENUMS(LHPF2, TACNA_LHPF2_INPUT1);
TACNA_MIXER_ENUMS(LHPF3, TACNA_LHPF3_INPUT1);
TACNA_MIXER_ENUMS(LHPF4, TACNA_LHPF4_INPUT1);

TACNA_MIXER_ENUMS(ASP1TX1, TACNA_ASP1TX1_INPUT1);
TACNA_MIXER_ENUMS(ASP1TX2, TACNA_ASP1TX2_INPUT1);
TACNA_MIXER_ENUMS(ASP1TX3, TACNA_ASP1TX3_INPUT1);
TACNA_MIXER_ENUMS(ASP1TX4, TACNA_ASP1TX4_INPUT1);
TACNA_MIXER_ENUMS(ASP1TX5, TACNA_ASP1TX5_INPUT1);
TACNA_MIXER_ENUMS(ASP1TX6, TACNA_ASP1TX6_INPUT1);
TACNA_MIXER_ENUMS(ASP1TX7, TACNA_ASP1TX7_INPUT1);
TACNA_MIXER_ENUMS(ASP1TX8, TACNA_ASP1TX8_INPUT1);

TACNA_MIXER_ENUMS(ASP2TX1, TACNA_ASP2TX1_INPUT1);
TACNA_MIXER_ENUMS(ASP2TX2, TACNA_ASP2TX2_INPUT1);
TACNA_MIXER_ENUMS(ASP2TX3, TACNA_ASP2TX3_INPUT1);
TACNA_MIXER_ENUMS(ASP2TX4, TACNA_ASP2TX4_INPUT1);
TACNA_MIXER_ENUMS(ASP2TX5, TACNA_ASP2TX5_INPUT1);
TACNA_MIXER_ENUMS(ASP2TX6, TACNA_ASP2TX6_INPUT1);
TACNA_MIXER_ENUMS(ASP2TX7, TACNA_ASP2TX7_INPUT1);
TACNA_MIXER_ENUMS(ASP2TX8, TACNA_ASP2TX8_INPUT1);

TACNA_MIXER_ENUMS(ASP3TX1, TACNA_ASP3TX1_INPUT1);
TACNA_MIXER_ENUMS(ASP3TX2, TACNA_ASP3TX2_INPUT1);
TACNA_MIXER_ENUMS(ASP3TX3, TACNA_ASP3TX3_INPUT1);
TACNA_MIXER_ENUMS(ASP3TX4, TACNA_ASP3TX4_INPUT1);
TACNA_MIXER_ENUMS(ASP3TX5, TACNA_ASP3TX5_INPUT1);
TACNA_MIXER_ENUMS(ASP3TX6, TACNA_ASP3TX6_INPUT1);
TACNA_MIXER_ENUMS(ASP3TX7, TACNA_ASP3TX7_INPUT1);
TACNA_MIXER_ENUMS(ASP3TX8, TACNA_ASP3TX8_INPUT1);

TACNA_MIXER_ENUMS(ASP4TX1, TACNA_ASP4TX1_INPUT1);
TACNA_MIXER_ENUMS(ASP4TX2, TACNA_ASP4TX2_INPUT1);
TACNA_MIXER_ENUMS(ASP4TX3, TACNA_ASP4TX3_INPUT1);
TACNA_MIXER_ENUMS(ASP4TX4, TACNA_ASP4TX4_INPUT1);
TACNA_MIXER_ENUMS(ASP4TX5, TACNA_ASP4TX5_INPUT1);
TACNA_MIXER_ENUMS(ASP4TX6, TACNA_ASP4TX6_INPUT1);
TACNA_MIXER_ENUMS(ASP4TX7, TACNA_ASP4TX7_INPUT1);
TACNA_MIXER_ENUMS(ASP4TX8, TACNA_ASP4TX8_INPUT1);

TACNA_MIXER_ENUMS(SLIMTX1, TACNA_SLIMTX1_INPUT1);
TACNA_MIXER_ENUMS(SLIMTX2, TACNA_SLIMTX2_INPUT1);
TACNA_MIXER_ENUMS(SLIMTX3, TACNA_SLIMTX3_INPUT1);
TACNA_MIXER_ENUMS(SLIMTX4, TACNA_SLIMTX4_INPUT1);
TACNA_MIXER_ENUMS(SLIMTX5, TACNA_SLIMTX5_INPUT1);
TACNA_MIXER_ENUMS(SLIMTX6, TACNA_SLIMTX6_INPUT1);
TACNA_MIXER_ENUMS(SLIMTX7, TACNA_SLIMTX7_INPUT1);
TACNA_MIXER_ENUMS(SLIMTX8, TACNA_SLIMTX8_INPUT1);

TACNA_MUX_ENUMS(ASRC1IN1L, TACNA_ASRC1_IN1L_INPUT1);
TACNA_MUX_ENUMS(ASRC1IN1R, TACNA_ASRC1_IN1R_INPUT1);
TACNA_MUX_ENUMS(ASRC1IN2L, TACNA_ASRC1_IN2L_INPUT1);
TACNA_MUX_ENUMS(ASRC1IN2R, TACNA_ASRC1_IN2R_INPUT1);

TACNA_MUX_ENUMS(ASRC2IN1L, CS48LX50_ASRC2_IN1L_INPUT1);
TACNA_MUX_ENUMS(ASRC2IN1R, CS48LX50_ASRC2_IN1R_INPUT1);
TACNA_MUX_ENUMS(ASRC2IN2L, CS48LX50_ASRC2_IN2L_INPUT1);
TACNA_MUX_ENUMS(ASRC2IN2R, CS48LX50_ASRC2_IN2R_INPUT1);

TACNA_MUX_ENUMS(ISRC1INT1, TACNA_ISRC1INT1_INPUT1);
TACNA_MUX_ENUMS(ISRC1INT2, TACNA_ISRC1INT2_INPUT1);
TACNA_MUX_ENUMS(ISRC1INT3, TACNA_ISRC1INT3_INPUT1);
TACNA_MUX_ENUMS(ISRC1INT4, TACNA_ISRC1INT4_INPUT1);

TACNA_MUX_ENUMS(ISRC1DEC1, TACNA_ISRC1DEC1_INPUT1);
TACNA_MUX_ENUMS(ISRC1DEC2, TACNA_ISRC1DEC2_INPUT1);
TACNA_MUX_ENUMS(ISRC1DEC3, TACNA_ISRC1DEC3_INPUT1);
TACNA_MUX_ENUMS(ISRC1DEC4, TACNA_ISRC1DEC4_INPUT1);

TACNA_MIXER_ENUMS(DSP1RX1, TACNA_DSP1RX1_INPUT1);
TACNA_MIXER_ENUMS(DSP1RX2, TACNA_DSP1RX2_INPUT1);
TACNA_MIXER_ENUMS(DSP1RX3, TACNA_DSP1RX3_INPUT1);
TACNA_MIXER_ENUMS(DSP1RX4, TACNA_DSP1RX4_INPUT1);
TACNA_MIXER_ENUMS(DSP1RX5, TACNA_DSP1RX5_INPUT1);
TACNA_MIXER_ENUMS(DSP1RX6, TACNA_DSP1RX6_INPUT1);
TACNA_MIXER_ENUMS(DSP1RX7, TACNA_DSP1RX7_INPUT1);
TACNA_MIXER_ENUMS(DSP1RX8, TACNA_DSP1RX8_INPUT1);
TACNA_MIXER_ENUMS(DSP1RX9, TACNA_DSP1RX9_INPUT1);

TACNA_MIXER_ENUMS(DSP2RX1, TACNA_DSP2RX1_INPUT1);
TACNA_MIXER_ENUMS(DSP2RX2, TACNA_DSP2RX2_INPUT1);
TACNA_MIXER_ENUMS(DSP2RX3, TACNA_DSP2RX3_INPUT1);
TACNA_MIXER_ENUMS(DSP2RX4, TACNA_DSP2RX4_INPUT1);
TACNA_MIXER_ENUMS(DSP2RX5, TACNA_DSP2RX5_INPUT1);
TACNA_MIXER_ENUMS(DSP2RX6, TACNA_DSP2RX6_INPUT1);
TACNA_MIXER_ENUMS(DSP2RX7, TACNA_DSP2RX7_INPUT1);
TACNA_MIXER_ENUMS(DSP2RX8, TACNA_DSP2RX8_INPUT1);

/*
 * ===========================================================================
 * dapm widgets
 * ===========================================================================
 */

static const struct snd_soc_dapm_widget clsic_dapm_widgets[] = {
SND_SOC_DAPM_SUPPLY("SYSCLK", TACNA_SYSTEM_CLOCK1, TACNA_SYSCLK_EN_SHIFT,
		    0, tacna_sysclk_ev,
		    SND_SOC_DAPM_POST_PMU | SND_SOC_DAPM_PRE_PMD),
SND_SOC_DAPM_SUPPLY("ASYNCCLK", TACNA_ASYNC_CLOCK1, TACNA_ASYNC_CLK_EN_SHIFT,
		    0, NULL, 0),
SND_SOC_DAPM_SUPPLY("OPCLK", TACNA_OUTPUT_SYS_CLK, TACNA_OPCLK_EN_SHIFT,
		    0, NULL, 0),
SND_SOC_DAPM_SUPPLY("ASYNCOPCLK", TACNA_OUTPUT_ASYNC_CLK,
		    TACNA_OPCLK_ASYNC_EN_SHIFT, 0, NULL, 0),
/*
 * we don't control DSPCLK, but define it for consistency with usual tacna-class
 * devices
 */
SND_SOC_DAPM_SUPPLY("DSPCLK", SND_SOC_NOPM, TACNA_DSP_CLK_EN_SHIFT,
		    0, NULL, 0),

SND_SOC_DAPM_REGULATOR_SUPPLY("MICVDD", 0, SND_SOC_DAPM_REGULATOR_BYPASS),

SND_SOC_DAPM_SUPPLY("MICBIAS1A", SND_SOC_NOPM, TACNA_MICB1A_EN_SHIFT,
		    0, clsic_micbias_ev,
		    SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_PRE_PMD),

SND_SOC_DAPM_SUPPLY("MICBIAS1B", SND_SOC_NOPM, TACNA_MICB1B_EN_SHIFT,
		    0, clsic_micbias_ev,
		    SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_PRE_PMD),

SND_SOC_DAPM_SUPPLY("MICBIAS1C", SND_SOC_NOPM, TACNA_MICB1C_EN_SHIFT,
		    0, clsic_micbias_ev,
		    SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_PRE_PMD),

SND_SOC_DAPM_SUPPLY("MICBIAS1D", SND_SOC_NOPM, TACNA_MICB1D_EN_SHIFT,
		    0, clsic_micbias_ev,
		    SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_PRE_PMD),

SND_SOC_DAPM_SIGGEN("TONE"),

SND_SOC_DAPM_INPUT("IN1L"),
SND_SOC_DAPM_INPUT("IN1R"),
SND_SOC_DAPM_INPUT("IN2L"),
SND_SOC_DAPM_INPUT("IN2R"),
SND_SOC_DAPM_INPUT("IN3L"),
SND_SOC_DAPM_INPUT("IN3R"),
SND_SOC_DAPM_INPUT("IN4L"),
SND_SOC_DAPM_INPUT("IN4R"),
SND_SOC_DAPM_INPUT("IN1_PDMCLK"),
SND_SOC_DAPM_INPUT("IN1_PDMDATA"),
SND_SOC_DAPM_INPUT("IN2_PDMCLK"),
SND_SOC_DAPM_INPUT("IN2_PDMDATA"),
SND_SOC_DAPM_INPUT("IN3_PDMCLK"),
SND_SOC_DAPM_INPUT("IN3_PDMDATA"),
SND_SOC_DAPM_INPUT("IN4_PDMCLK"),
SND_SOC_DAPM_INPUT("IN4_PDMDATA"),

SND_SOC_DAPM_OUTPUT("DRC1 Signal Activity"),
SND_SOC_DAPM_OUTPUT("DRC2 Signal Activity"),

SND_SOC_DAPM_OUTPUT("DSP Trigger Out"),

SND_SOC_DAPM_AIF_OUT("ASP1TX1", NULL, 0, TACNA_ASP1_ENABLES1,
		     TACNA_ASP1_TX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP1TX2", NULL, 0, TACNA_ASP1_ENABLES1,
		     TACNA_ASP1_TX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP1TX3", NULL, 0, TACNA_ASP1_ENABLES1,
		     TACNA_ASP1_TX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP1TX4", NULL, 0, TACNA_ASP1_ENABLES1,
		     TACNA_ASP1_TX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP1TX5", NULL, 0, TACNA_ASP1_ENABLES1,
		     TACNA_ASP1_TX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP1TX6", NULL, 0, TACNA_ASP1_ENABLES1,
		     TACNA_ASP1_TX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP1TX7", NULL, 0, TACNA_ASP1_ENABLES1,
		     TACNA_ASP1_TX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP1TX8", NULL, 0, TACNA_ASP1_ENABLES1,
		     TACNA_ASP1_TX8_EN_SHIFT, 0),

SND_SOC_DAPM_AIF_OUT("ASP2TX1", NULL, 0, TACNA_ASP2_ENABLES1,
		     TACNA_ASP2_TX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP2TX2", NULL, 0, TACNA_ASP2_ENABLES1,
		     TACNA_ASP2_TX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP2TX3", NULL, 0, TACNA_ASP2_ENABLES1,
		     TACNA_ASP2_TX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP2TX4", NULL, 0, TACNA_ASP2_ENABLES1,
		     TACNA_ASP2_TX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP2TX5", NULL, 0, TACNA_ASP2_ENABLES1,
		     TACNA_ASP2_TX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP2TX6", NULL, 0, TACNA_ASP2_ENABLES1,
		     TACNA_ASP2_TX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP2TX7", NULL, 0, TACNA_ASP2_ENABLES1,
		     TACNA_ASP2_TX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP2TX8", NULL, 0, TACNA_ASP2_ENABLES1,
		     TACNA_ASP2_TX8_EN_SHIFT, 0),

SND_SOC_DAPM_AIF_OUT("ASP3TX1", NULL, 0, TACNA_ASP3_ENABLES1,
		     TACNA_ASP3_TX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP3TX2", NULL, 0, TACNA_ASP3_ENABLES1,
		     TACNA_ASP3_TX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP3TX3", NULL, 0, TACNA_ASP3_ENABLES1,
		     TACNA_ASP3_TX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP3TX4", NULL, 0, TACNA_ASP3_ENABLES1,
		     TACNA_ASP3_TX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP3TX5", NULL, 0, TACNA_ASP3_ENABLES1,
		     TACNA_ASP3_TX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP3TX6", NULL, 0, TACNA_ASP3_ENABLES1,
		     TACNA_ASP3_TX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP3TX7", NULL, 0, TACNA_ASP3_ENABLES1,
		     TACNA_ASP3_TX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP3TX8", NULL, 0, TACNA_ASP3_ENABLES1,
		     TACNA_ASP3_TX8_EN_SHIFT, 0),

SND_SOC_DAPM_AIF_OUT("ASP4TX1", NULL, 0, TACNA_ASP4_ENABLES1,
		     TACNA_ASP4_TX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP4TX2", NULL, 0, TACNA_ASP4_ENABLES1,
		     TACNA_ASP4_TX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP4TX3", NULL, 0, TACNA_ASP4_ENABLES1,
		     TACNA_ASP4_TX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP4TX4", NULL, 0, TACNA_ASP4_ENABLES1,
		     TACNA_ASP4_TX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP4TX5", NULL, 0, TACNA_ASP4_ENABLES1,
		     TACNA_ASP4_TX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP4TX6", NULL, 0, TACNA_ASP4_ENABLES1,
		     TACNA_ASP4_TX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP4TX7", NULL, 0, TACNA_ASP4_ENABLES1,
		     TACNA_ASP4_TX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("ASP4TX8", NULL, 0, TACNA_ASP4_ENABLES1,
		     TACNA_ASP4_TX8_EN_SHIFT, 0),

SND_SOC_DAPM_AIF_OUT("SLIMTX1", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		     TACNA_SLIMTX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SLIMTX2", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		     TACNA_SLIMTX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SLIMTX3", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		     TACNA_SLIMTX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SLIMTX4", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		     TACNA_SLIMTX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SLIMTX5", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		     TACNA_SLIMTX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SLIMTX6", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		     TACNA_SLIMTX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SLIMTX7", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		     TACNA_SLIMTX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_OUT("SLIMTX8", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		     TACNA_SLIMTX8_EN_SHIFT, 0),

/*
 * mux_in widgets : arranged in the order of sources
 * specified in TACNA_MIXER_INPUT_ROUTES
 */

SND_SOC_DAPM_PGA("Tone Generator 1", TACNA_TONE_GENERATOR1,
		 TACNA_TONE1_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("Tone Generator 2", TACNA_TONE_GENERATOR1,
		 TACNA_TONE2_EN_SHIFT, 0, NULL, 0),

SND_SOC_DAPM_PGA_E("IN1L PGA", TACNA_INPUT_CONTROL, TACNA_IN1L_EN_SHIFT,
		   0, NULL, 0, tacna_in_ev,
		   SND_SOC_DAPM_PRE_PMD |
		   SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("IN1R PGA", TACNA_INPUT_CONTROL, TACNA_IN1R_EN_SHIFT,
		   0, NULL, 0, tacna_in_ev,
		   SND_SOC_DAPM_PRE_PMD |
		   SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("IN2L PGA", TACNA_INPUT_CONTROL, TACNA_IN2L_EN_SHIFT,
		   0, NULL, 0, tacna_in_ev,
		   SND_SOC_DAPM_PRE_PMD |
		   SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("IN2R PGA", TACNA_INPUT_CONTROL, TACNA_IN2R_EN_SHIFT,
		   0, NULL, 0, tacna_in_ev,
		   SND_SOC_DAPM_PRE_PMD |
		   SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("IN3L PGA", TACNA_INPUT_CONTROL, TACNA_IN3L_EN_SHIFT,
		   0, NULL, 0, tacna_in_ev,
		   SND_SOC_DAPM_PRE_PMD |
		   SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("IN3R PGA", TACNA_INPUT_CONTROL, TACNA_IN3R_EN_SHIFT,
		   0, NULL, 0, tacna_in_ev,
		   SND_SOC_DAPM_PRE_PMD |
		   SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("IN4L PGA", TACNA_INPUT_CONTROL, TACNA_IN4L_EN_SHIFT,
		   0, NULL, 0, tacna_in_ev,
		   SND_SOC_DAPM_PRE_PMD |
		   SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_POST_PMU),
SND_SOC_DAPM_PGA_E("IN4R PGA", TACNA_INPUT_CONTROL, TACNA_IN4R_EN_SHIFT,
		   0, NULL, 0, tacna_in_ev,
		   SND_SOC_DAPM_PRE_PMD |
		   SND_SOC_DAPM_PRE_PMU | SND_SOC_DAPM_POST_PMU),

SND_SOC_DAPM_AIF_IN("ASP1RX1", NULL, 0, TACNA_ASP1_ENABLES1,
		    TACNA_ASP1_RX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP1RX2", NULL, 0, TACNA_ASP1_ENABLES1,
		    TACNA_ASP1_RX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP1RX3", NULL, 0, TACNA_ASP1_ENABLES1,
		    TACNA_ASP1_RX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP1RX4", NULL, 0, TACNA_ASP1_ENABLES1,
		    TACNA_ASP1_RX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP1RX5", NULL, 0, TACNA_ASP1_ENABLES1,
		    TACNA_ASP1_RX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP1RX6", NULL, 0, TACNA_ASP1_ENABLES1,
		    TACNA_ASP1_RX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP1RX7", NULL, 0, TACNA_ASP1_ENABLES1,
		    TACNA_ASP1_RX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP1RX8", NULL, 0, TACNA_ASP1_ENABLES1,
		    TACNA_ASP1_RX8_EN_SHIFT, 0),

SND_SOC_DAPM_AIF_IN("ASP2RX1", NULL, 0, TACNA_ASP2_ENABLES1,
		    TACNA_ASP2_RX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP2RX2", NULL, 0, TACNA_ASP2_ENABLES1,
		    TACNA_ASP2_RX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP2RX3", NULL, 0, TACNA_ASP2_ENABLES1,
		    TACNA_ASP2_RX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP2RX4", NULL, 0, TACNA_ASP2_ENABLES1,
		    TACNA_ASP2_RX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP2RX5", NULL, 0, TACNA_ASP2_ENABLES1,
		    TACNA_ASP2_RX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP2RX6", NULL, 0, TACNA_ASP2_ENABLES1,
		    TACNA_ASP2_RX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP2RX7", NULL, 0, TACNA_ASP2_ENABLES1,
		    TACNA_ASP2_RX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP2RX8", NULL, 0, TACNA_ASP2_ENABLES1,
		    TACNA_ASP2_RX8_EN_SHIFT, 0),

SND_SOC_DAPM_AIF_IN("ASP3RX1", NULL, 0, TACNA_ASP3_ENABLES1,
		    TACNA_ASP3_RX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP3RX2", NULL, 0, TACNA_ASP3_ENABLES1,
		    TACNA_ASP3_RX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP3RX3", NULL, 0, TACNA_ASP3_ENABLES1,
		    TACNA_ASP3_RX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP3RX4", NULL, 0, TACNA_ASP3_ENABLES1,
		    TACNA_ASP3_RX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP3RX5", NULL, 0, TACNA_ASP3_ENABLES1,
		    TACNA_ASP3_RX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP3RX6", NULL, 0, TACNA_ASP3_ENABLES1,
		    TACNA_ASP3_RX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP3RX7", NULL, 0, TACNA_ASP3_ENABLES1,
		    TACNA_ASP3_RX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP3RX8", NULL, 0, TACNA_ASP3_ENABLES1,
		    TACNA_ASP3_RX8_EN_SHIFT, 0),

SND_SOC_DAPM_AIF_IN("ASP4RX1", NULL, 0, TACNA_ASP4_ENABLES1,
		    TACNA_ASP4_RX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP4RX2", NULL, 0, TACNA_ASP4_ENABLES1,
		    TACNA_ASP4_RX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP4RX3", NULL, 0, TACNA_ASP4_ENABLES1,
		    TACNA_ASP4_RX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP4RX4", NULL, 0, TACNA_ASP4_ENABLES1,
		    TACNA_ASP4_RX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP4RX5", NULL, 0, TACNA_ASP4_ENABLES1,
		    TACNA_ASP4_RX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP4RX6", NULL, 0, TACNA_ASP4_ENABLES1,
		    TACNA_ASP4_RX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP4RX7", NULL, 0, TACNA_ASP4_ENABLES1,
		    TACNA_ASP4_RX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("ASP4RX8", NULL, 0, TACNA_ASP4_ENABLES1,
		    TACNA_ASP4_RX8_EN_SHIFT, 0),

SND_SOC_DAPM_AIF_IN("SLIMRX1", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		    TACNA_SLIMRX1_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SLIMRX2", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		    TACNA_SLIMRX2_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SLIMRX3", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		    TACNA_SLIMRX3_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SLIMRX4", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		    TACNA_SLIMRX4_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SLIMRX5", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		    TACNA_SLIMRX5_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SLIMRX6", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		    TACNA_SLIMRX6_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SLIMRX7", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		    TACNA_SLIMRX7_EN_SHIFT, 0),
SND_SOC_DAPM_AIF_IN("SLIMRX8", NULL, 0, TACNA_SLIMBUS_CHANNEL_ENABLE,
		    TACNA_SLIMRX8_EN_SHIFT, 0),

SND_SOC_DAPM_PGA("ASRC1IN1L", TACNA_ASRC1_ENABLE,
		 TACNA_ASRC1_IN1L_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ASRC1IN1R", TACNA_ASRC1_ENABLE,
		 TACNA_ASRC1_IN1R_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ASRC1IN2L", TACNA_ASRC1_ENABLE,
		 TACNA_ASRC1_IN2L_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ASRC1IN2R", TACNA_ASRC1_ENABLE,
		 TACNA_ASRC1_IN2R_EN_SHIFT, 0, NULL, 0),

SND_SOC_DAPM_PGA("ASRC2IN1L", TACNA_ASRC2_ENABLE,
		 TACNA_ASRC2_IN1L_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ASRC2IN1R", TACNA_ASRC2_ENABLE,
		 TACNA_ASRC2_IN1R_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ASRC2IN2L", TACNA_ASRC2_ENABLE,
		 TACNA_ASRC2_IN2L_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ASRC2IN2R", TACNA_ASRC2_ENABLE,
		 TACNA_ASRC2_IN2R_EN_SHIFT, 0, NULL, 0),

SND_SOC_DAPM_PGA("ISRC1DEC1", TACNA_ISRC1_CONTROL2,
		 TACNA_ISRC1_DEC1_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ISRC1DEC2", TACNA_ISRC1_CONTROL2,
		 TACNA_ISRC1_DEC2_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ISRC1DEC3", TACNA_ISRC1_CONTROL2,
		 TACNA_ISRC1_DEC3_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ISRC1DEC4", TACNA_ISRC1_CONTROL2,
		 TACNA_ISRC1_DEC4_EN_SHIFT, 0, NULL, 0),

SND_SOC_DAPM_PGA("ISRC1INT1", TACNA_ISRC1_CONTROL2,
		 TACNA_ISRC1_INT1_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ISRC1INT2", TACNA_ISRC1_CONTROL2,
		 TACNA_ISRC1_INT2_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ISRC1INT3", TACNA_ISRC1_CONTROL2,
		 TACNA_ISRC1_INT3_EN_SHIFT, 0, NULL, 0),
SND_SOC_DAPM_PGA("ISRC1INT4", TACNA_ISRC1_CONTROL2,
		 TACNA_ISRC1_INT4_EN_SHIFT, 0, NULL, 0),

SND_SOC_DAPM_PGA_E("EQ1", TACNA_EQ_CONTROL1, TACNA_EQ1_EN_SHIFT, 0, NULL, 0,
		   tacna_eq_ev, SND_SOC_DAPM_PRE_PMU),
SND_SOC_DAPM_PGA_E("EQ2", TACNA_EQ_CONTROL1, TACNA_EQ2_EN_SHIFT, 0, NULL, 0,
		   tacna_eq_ev, SND_SOC_DAPM_PRE_PMU),
SND_SOC_DAPM_PGA_E("EQ3", TACNA_EQ_CONTROL1, TACNA_EQ3_EN_SHIFT, 0, NULL, 0,
		   tacna_eq_ev, SND_SOC_DAPM_PRE_PMU),
SND_SOC_DAPM_PGA_E("EQ4", TACNA_EQ_CONTROL1, TACNA_EQ4_EN_SHIFT, 0, NULL, 0,
		   tacna_eq_ev, SND_SOC_DAPM_PRE_PMU),

SND_SOC_DAPM_PGA("DRC1L", TACNA_DRC1_CONTROL1, TACNA_DRC1L_EN_SHIFT, 0,
		 NULL, 0),
SND_SOC_DAPM_PGA("DRC1R", TACNA_DRC1_CONTROL1, TACNA_DRC1R_EN_SHIFT, 0,
		 NULL, 0),
SND_SOC_DAPM_PGA("DRC2L", TACNA_DRC2_CONTROL1, TACNA_DRC2L_EN_SHIFT, 0,
		 NULL, 0),
SND_SOC_DAPM_PGA("DRC2R", TACNA_DRC2_CONTROL1, TACNA_DRC2R_EN_SHIFT, 0,
		 NULL, 0),

SND_SOC_DAPM_PGA("LHPF1", TACNA_LHPF_CONTROL1, TACNA_LHPF1_EN_SHIFT, 0,
		 NULL, 0),
SND_SOC_DAPM_PGA("LHPF2", TACNA_LHPF_CONTROL1, TACNA_LHPF2_EN_SHIFT, 0,
		 NULL, 0),
SND_SOC_DAPM_PGA("LHPF3", TACNA_LHPF_CONTROL1, TACNA_LHPF3_EN_SHIFT, 0,
		 NULL, 0),
SND_SOC_DAPM_PGA("LHPF4", TACNA_LHPF_CONTROL1, TACNA_LHPF4_EN_SHIFT, 0,
		 NULL, 0),

SND_SOC_DAPM_OUTPUT("DSP1"),
SND_SOC_DAPM_OUTPUT("DSP1RX1"),
SND_SOC_DAPM_OUTPUT("DSP1RX2"),
SND_SOC_DAPM_OUTPUT("DSP1RX3"),
SND_SOC_DAPM_OUTPUT("DSP1RX4"),
SND_SOC_DAPM_OUTPUT("DSP1RX5"),
SND_SOC_DAPM_OUTPUT("DSP1RX6"),
SND_SOC_DAPM_OUTPUT("DSP1RX7"),
SND_SOC_DAPM_OUTPUT("DSP1RX8"),
SND_SOC_DAPM_OUTPUT("DSP1RX9"),

/* end of ordered widget list */

TACNA_MIXER_WIDGETS(EQ1, "EQ1"),
TACNA_MIXER_WIDGETS(EQ2, "EQ2"),
TACNA_MIXER_WIDGETS(EQ3, "EQ3"),
TACNA_MIXER_WIDGETS(EQ4, "EQ4"),

TACNA_MIXER_WIDGETS(DRC1L, "DRC1L"),
TACNA_MIXER_WIDGETS(DRC1R, "DRC1R"),
TACNA_MIXER_WIDGETS(DRC2L, "DRC2L"),
TACNA_MIXER_WIDGETS(DRC2R, "DRC2R"),

SND_SOC_DAPM_SWITCH("DRC1 Activity Output", SND_SOC_NOPM, 0, 0,
		    &tacna_drc_activity_output_mux[0]),
SND_SOC_DAPM_SWITCH("DRC2 Activity Output", SND_SOC_NOPM, 0, 0,
		    &tacna_drc_activity_output_mux[1]),

TACNA_MIXER_WIDGETS(LHPF1, "LHPF1"),
TACNA_MIXER_WIDGETS(LHPF2, "LHPF2"),
TACNA_MIXER_WIDGETS(LHPF3, "LHPF3"),
TACNA_MIXER_WIDGETS(LHPF4, "LHPF4"),

TACNA_MIXER_WIDGETS(ASP1TX1, "ASP1TX1"),
TACNA_MIXER_WIDGETS(ASP1TX2, "ASP1TX2"),
TACNA_MIXER_WIDGETS(ASP1TX3, "ASP1TX3"),
TACNA_MIXER_WIDGETS(ASP1TX4, "ASP1TX4"),
TACNA_MIXER_WIDGETS(ASP1TX5, "ASP1TX5"),
TACNA_MIXER_WIDGETS(ASP1TX6, "ASP1TX6"),
TACNA_MIXER_WIDGETS(ASP1TX7, "ASP1TX7"),
TACNA_MIXER_WIDGETS(ASP1TX8, "ASP1TX8"),

TACNA_MIXER_WIDGETS(ASP2TX1, "ASP2TX1"),
TACNA_MIXER_WIDGETS(ASP2TX2, "ASP2TX2"),
TACNA_MIXER_WIDGETS(ASP2TX3, "ASP2TX3"),
TACNA_MIXER_WIDGETS(ASP2TX4, "ASP2TX4"),
TACNA_MIXER_WIDGETS(ASP2TX5, "ASP2TX5"),
TACNA_MIXER_WIDGETS(ASP2TX6, "ASP2TX6"),
TACNA_MIXER_WIDGETS(ASP2TX7, "ASP2TX7"),
TACNA_MIXER_WIDGETS(ASP2TX8, "ASP2TX8"),

TACNA_MIXER_WIDGETS(ASP3TX1, "ASP3TX1"),
TACNA_MIXER_WIDGETS(ASP3TX2, "ASP3TX2"),
TACNA_MIXER_WIDGETS(ASP3TX3, "ASP3TX3"),
TACNA_MIXER_WIDGETS(ASP3TX4, "ASP3TX4"),
TACNA_MIXER_WIDGETS(ASP3TX5, "ASP3TX5"),
TACNA_MIXER_WIDGETS(ASP3TX6, "ASP3TX6"),
TACNA_MIXER_WIDGETS(ASP3TX7, "ASP3TX7"),
TACNA_MIXER_WIDGETS(ASP3TX8, "ASP3TX8"),

TACNA_MIXER_WIDGETS(ASP4TX1, "ASP4TX1"),
TACNA_MIXER_WIDGETS(ASP4TX2, "ASP4TX2"),
TACNA_MIXER_WIDGETS(ASP4TX3, "ASP4TX3"),
TACNA_MIXER_WIDGETS(ASP4TX4, "ASP4TX4"),
TACNA_MIXER_WIDGETS(ASP4TX5, "ASP4TX5"),
TACNA_MIXER_WIDGETS(ASP4TX6, "ASP4TX6"),
TACNA_MIXER_WIDGETS(ASP4TX7, "ASP4TX7"),
TACNA_MIXER_WIDGETS(ASP4TX8, "ASP4TX8"),

TACNA_MIXER_WIDGETS(SLIMTX1, "SLIMTX1"),
TACNA_MIXER_WIDGETS(SLIMTX2, "SLIMTX2"),
TACNA_MIXER_WIDGETS(SLIMTX3, "SLIMTX3"),
TACNA_MIXER_WIDGETS(SLIMTX4, "SLIMTX4"),
TACNA_MIXER_WIDGETS(SLIMTX5, "SLIMTX5"),
TACNA_MIXER_WIDGETS(SLIMTX6, "SLIMTX6"),
TACNA_MIXER_WIDGETS(SLIMTX7, "SLIMTX7"),
TACNA_MIXER_WIDGETS(SLIMTX8, "SLIMTX8"),

TACNA_MUX_WIDGETS(ASRC1IN1L, "ASRC1IN1L"),
TACNA_MUX_WIDGETS(ASRC1IN1R, "ASRC1IN1R"),
TACNA_MUX_WIDGETS(ASRC1IN2L, "ASRC1IN2L"),
TACNA_MUX_WIDGETS(ASRC1IN2R, "ASRC1IN2R"),

TACNA_MUX_WIDGETS(ASRC2IN1L, "ASRC2IN1L"),
TACNA_MUX_WIDGETS(ASRC2IN1R, "ASRC2IN1R"),
TACNA_MUX_WIDGETS(ASRC2IN2L, "ASRC2IN2L"),
TACNA_MUX_WIDGETS(ASRC2IN2R, "ASRC2IN2R"),

TACNA_MUX_WIDGETS(ISRC1DEC1, "ISRC1DEC1"),
TACNA_MUX_WIDGETS(ISRC1DEC2, "ISRC1DEC2"),
TACNA_MUX_WIDGETS(ISRC1DEC3, "ISRC1DEC3"),
TACNA_MUX_WIDGETS(ISRC1DEC4, "ISRC1DEC4"),

TACNA_MUX_WIDGETS(ISRC1INT1, "ISRC1INT1"),
TACNA_MUX_WIDGETS(ISRC1INT2, "ISRC1INT2"),
TACNA_MUX_WIDGETS(ISRC1INT3, "ISRC1INT3"),
TACNA_MUX_WIDGETS(ISRC1INT4, "ISRC1INT4"),

TACNA_MIXER_WIDGETS(DSP1RX1, "DSP1RX1"),
TACNA_MIXER_WIDGETS(DSP1RX2, "DSP1RX2"),
TACNA_MIXER_WIDGETS(DSP1RX3, "DSP1RX3"),
TACNA_MIXER_WIDGETS(DSP1RX4, "DSP1RX4"),
TACNA_MIXER_WIDGETS(DSP1RX5, "DSP1RX5"),
TACNA_MIXER_WIDGETS(DSP1RX6, "DSP1RX6"),
TACNA_MIXER_WIDGETS(DSP1RX7, "DSP1RX7"),
TACNA_MIXER_WIDGETS(DSP1RX8, "DSP1RX8"),
TACNA_MIXER_WIDGETS(DSP1RX9, "DSP1RX9"),

TACNA_MIXER_WIDGETS(DSP2RX1, "DSP2RX1"),
TACNA_MIXER_WIDGETS(DSP2RX2, "DSP2RX2"),
TACNA_MIXER_WIDGETS(DSP2RX3, "DSP2RX3"),
TACNA_MIXER_WIDGETS(DSP2RX4, "DSP2RX4"),
TACNA_MIXER_WIDGETS(DSP2RX5, "DSP2RX5"),
TACNA_MIXER_WIDGETS(DSP2RX6, "DSP2RX6"),
TACNA_MIXER_WIDGETS(DSP2RX7, "DSP2RX7"),
TACNA_MIXER_WIDGETS(DSP2RX8, "DSP2RX8"),

SND_SOC_DAPM_OUTPUT("MICSUPP"),
}; /* end of clsic_dapm_widgets[] */

static const struct snd_soc_dapm_widget clsic_dapm_widgets_dsp2_visible[] = {
WM_HALO("DSP2", 1, clsic_dsp_power_ev),

SND_SOC_DAPM_SWITCH("DSP2 Trigger Output", SND_SOC_NOPM, 0, 0,
		    &tacna_dsp_trigger_output_mux[1]),
};

static const struct snd_soc_dapm_widget clsic_dapm_widgets_dsp2_hidden[] = {
SND_SOC_DAPM_OUTPUT("DSP2"),
SND_SOC_DAPM_OUTPUT("DSP2RX1"),
SND_SOC_DAPM_OUTPUT("DSP2RX2"),
SND_SOC_DAPM_OUTPUT("DSP2RX3"),
SND_SOC_DAPM_OUTPUT("DSP2RX4"),
SND_SOC_DAPM_OUTPUT("DSP2RX5"),
SND_SOC_DAPM_OUTPUT("DSP2RX6"),
SND_SOC_DAPM_OUTPUT("DSP2RX7"),
SND_SOC_DAPM_OUTPUT("DSP2RX8"),
};

#define TACNA_MIXER_INPUT_ROUTES(name) \
	{ name, "Tone Generator 1", "Tone Generator 1" }, \
	{ name, "Tone Generator 2", "Tone Generator 2" }, \
	{ name, "IN1L", "IN1L PGA" }, \
	{ name, "IN1R", "IN1R PGA" }, \
	{ name, "IN2L", "IN2L PGA" }, \
	{ name, "IN2R", "IN2R PGA" }, \
	{ name, "IN3L", "IN3L PGA" }, \
	{ name, "IN3R", "IN3R PGA" }, \
	{ name, "IN4L", "IN4L PGA" }, \
	{ name, "IN4R", "IN4R PGA" }, \
	{ name, "ASP1RX1", "ASP1RX1" }, \
	{ name, "ASP1RX2", "ASP1RX2" }, \
	{ name, "ASP1RX3", "ASP1RX3" }, \
	{ name, "ASP1RX4", "ASP1RX4" }, \
	{ name, "ASP1RX5", "ASP1RX5" }, \
	{ name, "ASP1RX6", "ASP1RX6" }, \
	{ name, "ASP1RX7", "ASP1RX7" }, \
	{ name, "ASP1RX8", "ASP1RX8" }, \
	{ name, "ASP2RX1", "ASP2RX1" }, \
	{ name, "ASP2RX2", "ASP2RX2" }, \
	{ name, "ASP2RX3", "ASP2RX3" }, \
	{ name, "ASP2RX4", "ASP2RX4" }, \
	{ name, "ASP2RX5", "ASP2RX5" }, \
	{ name, "ASP2RX6", "ASP2RX6" }, \
	{ name, "ASP2RX7", "ASP2RX7" }, \
	{ name, "ASP2RX8", "ASP2RX8" }, \
	{ name, "ASP3RX1", "ASP3RX1" }, \
	{ name, "ASP3RX2", "ASP3RX2" }, \
	{ name, "ASP3RX3", "ASP3RX3" }, \
	{ name, "ASP3RX4", "ASP3RX4" }, \
	{ name, "ASP3RX5", "ASP3RX5" }, \
	{ name, "ASP3RX6", "ASP3RX6" }, \
	{ name, "ASP3RX7", "ASP3RX7" }, \
	{ name, "ASP3RX8", "ASP3RX8" }, \
	{ name, "ASP4RX1", "ASP4RX1" }, \
	{ name, "ASP4RX2", "ASP4RX2" }, \
	{ name, "ASP4RX3", "ASP4RX3" }, \
	{ name, "ASP4RX4", "ASP4RX4" }, \
	{ name, "ASP4RX5", "ASP4RX5" }, \
	{ name, "ASP4RX6", "ASP4RX6" }, \
	{ name, "ASP4RX7", "ASP4RX7" }, \
	{ name, "ASP4RX8", "ASP4RX8" }, \
	{ name, "SLIMRX1", "SLIMRX1" }, \
	{ name, "SLIMRX2", "SLIMRX2" }, \
	{ name, "SLIMRX3", "SLIMRX3" }, \
	{ name, "SLIMRX4", "SLIMRX4" }, \
	{ name, "SLIMRX5", "SLIMRX5" }, \
	{ name, "SLIMRX6", "SLIMRX6" }, \
	{ name, "SLIMRX7", "SLIMRX7" }, \
	{ name, "SLIMRX8", "SLIMRX8" }, \
	{ name, "ASRC1IN1L", "ASRC1IN1L" }, \
	{ name, "ASRC1IN1R", "ASRC1IN1R" }, \
	{ name, "ASRC1IN2L", "ASRC1IN2L" }, \
	{ name, "ASRC1IN2R", "ASRC1IN2R" }, \
	{ name, "ASRC2IN1L", "ASRC2IN1L" }, \
	{ name, "ASRC2IN1R", "ASRC2IN1R" }, \
	{ name, "ASRC2IN2L", "ASRC2IN2L" }, \
	{ name, "ASRC2IN2R", "ASRC2IN2R" }, \
	{ name, "ISRC1DEC1", "ISRC1DEC1" }, \
	{ name, "ISRC1DEC2", "ISRC1DEC2" }, \
	{ name, "ISRC1DEC3", "ISRC1DEC3" }, \
	{ name, "ISRC1DEC4", "ISRC1DEC4" }, \
	{ name, "ISRC1INT1", "ISRC1INT1" }, \
	{ name, "ISRC1INT2", "ISRC1INT2" }, \
	{ name, "ISRC1INT3", "ISRC1INT3" }, \
	{ name, "ISRC1INT4", "ISRC1INT4" }, \
	{ name, "EQ1", "EQ1" }, \
	{ name, "EQ2", "EQ2" }, \
	{ name, "EQ3", "EQ3" }, \
	{ name, "EQ4", "EQ4" }, \
	{ name, "DRC1L", "DRC1L" }, \
	{ name, "DRC1R", "DRC1R" }, \
	{ name, "DRC2L", "DRC2L" }, \
	{ name, "DRC2R", "DRC2R" }, \
	{ name, "LHPF1", "LHPF1" }, \
	{ name, "LHPF2", "LHPF2" }, \
	{ name, "LHPF3", "LHPF3" }, \
	{ name, "LHPF4", "LHPF4" }, \
	{ name, "DSP1.1", "DSP1" }, \
	{ name, "DSP1.2", "DSP1" }, \
	{ name, "DSP1.3", "DSP1" }, \
	{ name, "DSP1.4", "DSP1" }, \
	{ name, "DSP1.5", "DSP1" }, \
	{ name, "DSP1.6", "DSP1" }, \
	{ name, "DSP1.7", "DSP1" }, \
	{ name, "DSP1.8", "DSP1" }, \
	{ name, "DSP2.1", "DSP2" }, \
	{ name, "DSP2.2", "DSP2" }, \
	{ name, "DSP2.3", "DSP2" }, \
	{ name, "DSP2.4", "DSP2" }, \
	{ name, "DSP2.5", "DSP2" }, \
	{ name, "DSP2.6", "DSP2" }, \
	{ name, "DSP2.7", "DSP2" }, \
	{ name, "DSP2.8", "DSP2" }

	/*
	 * XXX what happened to:
	 * { name, "DSP1.9", "DSP1" },
	 * is it needed?
	 */

static const struct snd_soc_dapm_route clsic_dapm_routes[] = {
	/* Internal clock domains */
	{ "ASRC1IN1L", NULL, "SYSCLK" },
	{ "ASRC1IN1R", NULL, "SYSCLK" },
	{ "ASRC1IN2L", NULL, "SYSCLK" },
	{ "ASRC1IN2R", NULL, "SYSCLK" },
	{ "ASRC1IN1L", NULL, "ASYNCCLK" },
	{ "ASRC1IN1R", NULL, "ASYNCCLK" },
	{ "ASRC1IN2L", NULL, "ASYNCCLK" },
	{ "ASRC1IN2R", NULL, "ASYNCCLK" },
	{ "ASRC2IN1L", NULL, "SYSCLK" },
	{ "ASRC2IN1R", NULL, "SYSCLK" },
	{ "ASRC2IN2L", NULL, "SYSCLK" },
	{ "ASRC2IN2R", NULL, "SYSCLK" },
	{ "ASRC2IN1L", NULL, "ASYNCCLK" },
	{ "ASRC2IN1R", NULL, "ASYNCCLK" },
	{ "ASRC2IN2L", NULL, "ASYNCCLK" },
	{ "ASRC2IN2R", NULL, "ASYNCCLK" },
	{ "IN1L", NULL, "SYSCLK" },
	{ "IN1R", NULL, "SYSCLK" },
	{ "IN2L", NULL, "SYSCLK" },
	{ "IN2R", NULL, "SYSCLK" },
	{ "IN3L", NULL, "SYSCLK" },
	{ "IN3R", NULL, "SYSCLK" },
	{ "IN4L", NULL, "SYSCLK" },
	{ "IN4R", NULL, "SYSCLK" },

	{ "IN1_PDMCLK", NULL, "SYSCLK" },
	{ "IN1_PDMDATA", NULL, "SYSCLK" },
	{ "IN2_PDMCLK", NULL, "SYSCLK" },
	{ "IN2_PDMDATA", NULL, "SYSCLK" },
	{ "IN3_PDMCLK", NULL, "SYSCLK" },
	{ "IN3_PDMDATA", NULL, "SYSCLK" },
	{ "IN4_PDMCLK", NULL, "SYSCLK" },
	{ "IN4_PDMDATA", NULL, "SYSCLK" },

	{ "MICBIAS1A", NULL, "MICVDD" },
	{ "MICBIAS1B", NULL, "MICVDD" },
	{ "MICBIAS1C", NULL, "MICVDD" },
	{ "MICBIAS1D", NULL, "MICVDD" },

	{ "Tone Generator 1", NULL, "SYSCLK" },
	{ "Tone Generator 2", NULL, "SYSCLK" },

	{ "Tone Generator 1", NULL, "TONE" },
	{ "Tone Generator 2", NULL, "TONE" },

	{ "ASP1 Capture", NULL, "ASP1TX1" },
	{ "ASP1 Capture", NULL, "ASP1TX2" },
	{ "ASP1 Capture", NULL, "ASP1TX3" },
	{ "ASP1 Capture", NULL, "ASP1TX4" },
	{ "ASP1 Capture", NULL, "ASP1TX5" },
	{ "ASP1 Capture", NULL, "ASP1TX6" },
	{ "ASP1 Capture", NULL, "ASP1TX7" },
	{ "ASP1 Capture", NULL, "ASP1TX8" },

	{ "ASP1RX1", NULL, "ASP1 Playback" },
	{ "ASP1RX2", NULL, "ASP1 Playback" },
	{ "ASP1RX3", NULL, "ASP1 Playback" },
	{ "ASP1RX4", NULL, "ASP1 Playback" },
	{ "ASP1RX5", NULL, "ASP1 Playback" },
	{ "ASP1RX6", NULL, "ASP1 Playback" },
	{ "ASP1RX7", NULL, "ASP1 Playback" },
	{ "ASP1RX8", NULL, "ASP1 Playback" },

	{ "ASP2 Capture", NULL, "ASP2TX1" },
	{ "ASP2 Capture", NULL, "ASP2TX2" },
	{ "ASP2 Capture", NULL, "ASP2TX3" },
	{ "ASP2 Capture", NULL, "ASP2TX4" },
	{ "ASP2 Capture", NULL, "ASP2TX5" },
	{ "ASP2 Capture", NULL, "ASP2TX6" },
	{ "ASP2 Capture", NULL, "ASP2TX7" },
	{ "ASP2 Capture", NULL, "ASP2TX8" },

	{ "ASP2RX1", NULL, "ASP2 Playback" },
	{ "ASP2RX2", NULL, "ASP2 Playback" },
	{ "ASP2RX3", NULL, "ASP2 Playback" },
	{ "ASP2RX4", NULL, "ASP2 Playback" },
	{ "ASP2RX5", NULL, "ASP2 Playback" },
	{ "ASP2RX6", NULL, "ASP2 Playback" },
	{ "ASP2RX7", NULL, "ASP2 Playback" },
	{ "ASP2RX8", NULL, "ASP2 Playback" },

	{ "ASP3 Capture", NULL, "ASP3TX1" },
	{ "ASP3 Capture", NULL, "ASP3TX2" },
	{ "ASP3 Capture", NULL, "ASP3TX3" },
	{ "ASP3 Capture", NULL, "ASP3TX4" },
	{ "ASP3 Capture", NULL, "ASP3TX5" },
	{ "ASP3 Capture", NULL, "ASP3TX6" },
	{ "ASP3 Capture", NULL, "ASP3TX7" },
	{ "ASP3 Capture", NULL, "ASP3TX8" },

	{ "ASP3RX1", NULL, "ASP3 Playback" },
	{ "ASP3RX2", NULL, "ASP3 Playback" },
	{ "ASP3RX3", NULL, "ASP3 Playback" },
	{ "ASP3RX4", NULL, "ASP3 Playback" },
	{ "ASP3RX5", NULL, "ASP3 Playback" },
	{ "ASP3RX6", NULL, "ASP3 Playback" },
	{ "ASP3RX7", NULL, "ASP3 Playback" },
	{ "ASP3RX8", NULL, "ASP3 Playback" },

	{ "ASP4 Capture", NULL, "ASP4TX1" },
	{ "ASP4 Capture", NULL, "ASP4TX2" },
	{ "ASP4 Capture", NULL, "ASP4TX3" },
	{ "ASP4 Capture", NULL, "ASP4TX4" },
	{ "ASP4 Capture", NULL, "ASP4TX5" },
	{ "ASP4 Capture", NULL, "ASP4TX6" },
	{ "ASP4 Capture", NULL, "ASP4TX7" },
	{ "ASP4 Capture", NULL, "ASP4TX8" },

	{ "ASP4RX1", NULL, "ASP4 Playback" },
	{ "ASP4RX2", NULL, "ASP4 Playback" },
	{ "ASP4RX3", NULL, "ASP4 Playback" },
	{ "ASP4RX4", NULL, "ASP4 Playback" },
	{ "ASP4RX5", NULL, "ASP4 Playback" },
	{ "ASP4RX6", NULL, "ASP4 Playback" },
	{ "ASP4RX7", NULL, "ASP4 Playback" },
	{ "ASP4RX8", NULL, "ASP4 Playback" },

	{ "ASP1 Playback", NULL, "SYSCLK" },
	{ "ASP2 Playback", NULL, "SYSCLK" },
	{ "ASP3 Playback", NULL, "SYSCLK" },
	{ "ASP4 Playback", NULL, "SYSCLK" },
	{ "Slim1 Playback", NULL, "SYSCLK" },
	{ "Slim2 Playback", NULL, "SYSCLK" },
	{ "Slim3 Playback", NULL, "SYSCLK" },

	{ "ASP1 Capture", NULL, "SYSCLK" },
	{ "ASP2 Capture", NULL, "SYSCLK" },
	{ "ASP3 Capture", NULL, "SYSCLK" },
	{ "ASP4 Capture", NULL, "SYSCLK" },

	{ "Slim1 Capture", NULL, "SYSCLK" },
	{ "Slim2 Capture", NULL, "SYSCLK" },
	{ "Slim3 Capture", NULL, "SYSCLK" },

	{ "IN1L PGA", NULL, "IN1L" },
	{ "IN1R PGA", NULL, "IN1R" },
	{ "IN2L PGA", NULL, "IN2L" },
	{ "IN2R PGA", NULL, "IN2R" },
	{ "IN3L PGA", NULL, "IN3L" },
	{ "IN3R PGA", NULL, "IN3R" },
	{ "IN4L PGA", NULL, "IN4L" },
	{ "IN4R PGA", NULL, "IN4R" },

	{ "IN1L", NULL, "IN1_PDMCLK" },
	{ "IN1L", NULL, "IN1_PDMDATA" },
	{ "IN1R", NULL, "IN1_PDMCLK" },
	{ "IN1R", NULL, "IN1_PDMDATA" },
	{ "IN2L", NULL, "IN2_PDMCLK" },
	{ "IN2L", NULL, "IN2_PDMDATA" },
	{ "IN2R", NULL, "IN2_PDMCLK" },
	{ "IN2R", NULL, "IN2_PDMDATA" },
	{ "IN3L", NULL, "IN3_PDMCLK" },
	{ "IN3L", NULL, "IN3_PDMDATA" },
	{ "IN3R", NULL, "IN3_PDMCLK" },
	{ "IN3R", NULL, "IN3_PDMDATA" },
	{ "IN4L", NULL, "IN4_PDMCLK" },
	{ "IN4L", NULL, "IN4_PDMDATA" },
	{ "IN4R", NULL, "IN4_PDMCLK" },
	{ "IN4R", NULL, "IN4_PDMDATA" },

	TACNA_MIXER_ROUTES("ASP1TX1", "ASP1TX1"),
	TACNA_MIXER_ROUTES("ASP1TX2", "ASP1TX2"),
	TACNA_MIXER_ROUTES("ASP1TX3", "ASP1TX3"),
	TACNA_MIXER_ROUTES("ASP1TX4", "ASP1TX4"),
	TACNA_MIXER_ROUTES("ASP1TX5", "ASP1TX5"),
	TACNA_MIXER_ROUTES("ASP1TX6", "ASP1TX6"),
	TACNA_MIXER_ROUTES("ASP1TX7", "ASP1TX7"),
	TACNA_MIXER_ROUTES("ASP1TX8", "ASP1TX8"),

	TACNA_MIXER_ROUTES("ASP2TX1", "ASP2TX1"),
	TACNA_MIXER_ROUTES("ASP2TX2", "ASP2TX2"),
	TACNA_MIXER_ROUTES("ASP2TX3", "ASP2TX3"),
	TACNA_MIXER_ROUTES("ASP2TX4", "ASP2TX4"),
	TACNA_MIXER_ROUTES("ASP2TX5", "ASP2TX5"),
	TACNA_MIXER_ROUTES("ASP2TX6", "ASP2TX6"),
	TACNA_MIXER_ROUTES("ASP2TX7", "ASP2TX7"),
	TACNA_MIXER_ROUTES("ASP2TX8", "ASP2TX8"),

	TACNA_MIXER_ROUTES("ASP3TX1", "ASP3TX1"),
	TACNA_MIXER_ROUTES("ASP3TX2", "ASP3TX2"),
	TACNA_MIXER_ROUTES("ASP3TX3", "ASP3TX3"),
	TACNA_MIXER_ROUTES("ASP3TX4", "ASP3TX4"),
	TACNA_MIXER_ROUTES("ASP3TX5", "ASP3TX5"),
	TACNA_MIXER_ROUTES("ASP3TX6", "ASP3TX6"),
	TACNA_MIXER_ROUTES("ASP3TX7", "ASP3TX7"),
	TACNA_MIXER_ROUTES("ASP3TX8", "ASP3TX8"),

	TACNA_MIXER_ROUTES("ASP4TX1", "ASP4TX1"),
	TACNA_MIXER_ROUTES("ASP4TX2", "ASP4TX2"),
	TACNA_MIXER_ROUTES("ASP4TX3", "ASP4TX3"),
	TACNA_MIXER_ROUTES("ASP4TX4", "ASP4TX4"),
	TACNA_MIXER_ROUTES("ASP4TX5", "ASP4TX5"),
	TACNA_MIXER_ROUTES("ASP4TX6", "ASP4TX6"),
	TACNA_MIXER_ROUTES("ASP4TX7", "ASP4TX7"),
	TACNA_MIXER_ROUTES("ASP4TX8", "ASP4TX8"),

	TACNA_MIXER_ROUTES("SLIMTX1", "SLIMTX1"),
	TACNA_MIXER_ROUTES("SLIMTX2", "SLIMTX2"),
	TACNA_MIXER_ROUTES("SLIMTX3", "SLIMTX3"),
	TACNA_MIXER_ROUTES("SLIMTX4", "SLIMTX4"),
	TACNA_MIXER_ROUTES("SLIMTX5", "SLIMTX5"),
	TACNA_MIXER_ROUTES("SLIMTX6", "SLIMTX6"),
	TACNA_MIXER_ROUTES("SLIMTX7", "SLIMTX7"),
	TACNA_MIXER_ROUTES("SLIMTX8", "SLIMTX8"),

	TACNA_MIXER_ROUTES("EQ1", "EQ1"),
	TACNA_MIXER_ROUTES("EQ2", "EQ2"),
	TACNA_MIXER_ROUTES("EQ3", "EQ3"),
	TACNA_MIXER_ROUTES("EQ4", "EQ4"),

	TACNA_MIXER_ROUTES("DRC1L", "DRC1L"),
	TACNA_MIXER_ROUTES("DRC1R", "DRC1R"),
	TACNA_MIXER_ROUTES("DRC2L", "DRC2L"),
	TACNA_MIXER_ROUTES("DRC2R", "DRC2R"),

	TACNA_MIXER_ROUTES("LHPF1", "LHPF1"),
	TACNA_MIXER_ROUTES("LHPF2", "LHPF2"),
	TACNA_MIXER_ROUTES("LHPF3", "LHPF3"),
	TACNA_MIXER_ROUTES("LHPF4", "LHPF4"),

	TACNA_MUX_ROUTES("ASRC1IN1L", "ASRC1IN1L"),
	TACNA_MUX_ROUTES("ASRC1IN1R", "ASRC1IN1R"),
	TACNA_MUX_ROUTES("ASRC1IN2L", "ASRC1IN2L"),
	TACNA_MUX_ROUTES("ASRC1IN2R", "ASRC1IN2R"),

	TACNA_MUX_ROUTES("ASRC2IN1L", "ASRC2IN1L"),
	TACNA_MUX_ROUTES("ASRC2IN1R", "ASRC2IN1R"),
	TACNA_MUX_ROUTES("ASRC2IN2L", "ASRC2IN2L"),
	TACNA_MUX_ROUTES("ASRC2IN2R", "ASRC2IN2R"),

	TACNA_MIXER_ROUTES("DSP1", "DSP1RX1"),
	TACNA_MIXER_ROUTES("DSP1", "DSP1RX2"),
	TACNA_MIXER_ROUTES("DSP1", "DSP1RX3"),
	TACNA_MIXER_ROUTES("DSP1", "DSP1RX4"),
	TACNA_MIXER_ROUTES("DSP1", "DSP1RX5"),
	TACNA_MIXER_ROUTES("DSP1", "DSP1RX6"),
	TACNA_MIXER_ROUTES("DSP1", "DSP1RX7"),
	TACNA_MIXER_ROUTES("DSP1", "DSP1RX8"),
	TACNA_MIXER_ROUTES("DSP1", "DSP1RX9"),

	TACNA_MUX_ROUTES("ISRC1INT1", "ISRC1INT1"),
	TACNA_MUX_ROUTES("ISRC1INT2", "ISRC1INT2"),
	TACNA_MUX_ROUTES("ISRC1INT3", "ISRC1INT3"),
	TACNA_MUX_ROUTES("ISRC1INT4", "ISRC1INT4"),

	TACNA_MUX_ROUTES("ISRC1DEC1", "ISRC1DEC1"),
	TACNA_MUX_ROUTES("ISRC1DEC2", "ISRC1DEC2"),
	TACNA_MUX_ROUTES("ISRC1DEC3", "ISRC1DEC3"),
	TACNA_MUX_ROUTES("ISRC1DEC4", "ISRC1DEC4"),

	{ "MICSUPP", NULL, "SYSCLK" },

	{ "DRC1 Signal Activity", NULL, "DRC1 Activity Output" },
	{ "DRC2 Signal Activity", NULL, "DRC2 Activity Output" },
	{ "DRC1 Activity Output", "Switch", "DRC1L" },
	{ "DRC1 Activity Output", "Switch", "DRC1R" },
	{ "DRC2 Activity Output", "Switch", "DRC2L" },
	{ "DRC2 Activity Output", "Switch", "DRC2R" },
}; /* end of clsic_dapm_routes */

static const struct snd_soc_dapm_route clsic_dapm_routes_dsp2_visible[] = {
	TACNA_DSP_ROUTES_1_8("DSP2"),

	{ "DSP Trigger Out", NULL, "DSP2 Trigger Output" },
	{ "DSP2 Trigger Output", "Switch", "DSP2" },
};

static const struct snd_soc_dapm_route clsic_dapm_routes_dsp2_hidden[] = {
	TACNA_MIXER_ROUTES("DSP2", "DSP2RX1"),
	TACNA_MIXER_ROUTES("DSP2", "DSP2RX2"),
	TACNA_MIXER_ROUTES("DSP2", "DSP2RX3"),
	TACNA_MIXER_ROUTES("DSP2", "DSP2RX4"),
	TACNA_MIXER_ROUTES("DSP2", "DSP2RX5"),
	TACNA_MIXER_ROUTES("DSP2", "DSP2RX6"),
	TACNA_MIXER_ROUTES("DSP2", "DSP2RX7"),
	TACNA_MIXER_ROUTES("DSP2", "DSP2RX8"),
};

static struct snd_soc_dai_driver clsic_dai[] = {
	{
		.name = "clsic-asp1",
		.id = 1,
		.base = TACNA_ASP1_ENABLES1,
		.playback = {
			.stream_name = "ASP1 Playback",
			.channels_min = 1,
			.channels_max = 8,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		},
		.capture = {
			.stream_name = "ASP1 Capture",
			.channels_min = 1,
			.channels_max = 8,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		 },
		.ops = &tacna_dai_ops,
		.symmetric_rates = 1,
		.symmetric_samplebits = 1,
	},
	{
		.name = "clsic-asp2",
		.id = 2,
		.base = TACNA_ASP2_ENABLES1,
		.playback = {
			.stream_name = "ASP2 Playback",
			.channels_min = 1,
			.channels_max = 8,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		},
		.capture = {
			.stream_name = "ASP2 Capture",
			.channels_min = 1,
			.channels_max = 8,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		 },
		.ops = &tacna_dai_ops,
		.symmetric_rates = 1,
		.symmetric_samplebits = 1,
	},
	{
		.name = "clsic-asp3",
		.id = 3,
		.base = TACNA_ASP3_ENABLES1,
		.playback = {
			.stream_name = "ASP3 Playback",
			.channels_min = 1,
			.channels_max = 8,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		},
		.capture = {
			.stream_name = "ASP3 Capture",
			.channels_min = 1,
			.channels_max = 8,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		 },
		.ops = &tacna_dai_ops,
		.symmetric_rates = 1,
		.symmetric_samplebits = 1,
	},
	{
		.name = "clsic-asp4",
		.id = 4,
		.base = TACNA_ASP4_ENABLES1,
		.playback = {
			.stream_name = "ASP4 Playback",
			.channels_min = 1,
			.channels_max = 8,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		},
		.capture = {
			.stream_name = "ASP4 Capture",
			.channels_min = 1,
			.channels_max = 8,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		 },
		.ops = &tacna_dai_ops,
		.symmetric_rates = 1,
		.symmetric_samplebits = 1,
	},
	{
		.name = "clsic-slim1",
		.id = 5,
		.playback = {
			.stream_name = "Slim1 Playback",
			.channels_min = 1,
			.channels_max = 4,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		},
		.capture = {
			.stream_name = "Slim1 Capture",
			.channels_min = 1,
			.channels_max = 4,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		 },
		.ops = &tacna_simple_dai_ops,
	},
	{
		.name = "clsic-slim2",
		.id = 6,
		.playback = {
			.stream_name = "Slim2 Playback",
			.channels_min = 1,
			.channels_max = 2,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		},
		.capture = {
			.stream_name = "Slim2 Capture",
			.channels_min = 1,
			.channels_max = 2,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		 },
		.ops = &tacna_simple_dai_ops,
	},
	{
		.name = "clsic-slim3",
		.id = 7,
		.playback = {
			.stream_name = "Slim3 Playback",
			.channels_min = 1,
			.channels_max = 2,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		},
		.capture = {
			.stream_name = "Slim3 Capture",
			.channels_min = 1,
			.channels_max = 2,
			.rates = TACNA_RATES,
			.formats = TACNA_FORMATS,
		 },
		.ops = &tacna_simple_dai_ops,
	},
};

static const struct soc_enum clsic_dsp1_rx_rate_enum[] = {
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_RX1, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_RX2, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_RX3, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_RX4, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_RX5, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text,  tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_RX6, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_RX7, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_RX8, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_RX9, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
};

static const struct soc_enum clsic_dsp1_tx_rate_enum[] = {
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_TX1, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_TX2, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_TX3, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_TX4, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_TX5, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_TX6, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_TX7, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_TX8, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP1_SAMPLE_RATE_TX9, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
};

static const struct soc_enum clsic_dsp2_rx_rate_enum[] = {
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_RX1, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_RX2, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_RX3, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_RX4, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_RX5, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text,  tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_RX6, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_RX7, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_RX8, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
};

static const struct soc_enum clsic_dsp2_tx_rate_enum[] = {
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_TX1, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_TX2, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_TX3, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_TX4, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_TX5, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_TX6, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_TX7, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
	SOC_VALUE_ENUM_SINGLE(TACNA_DSP2_SAMPLE_RATE_TX8, 0,
			      TACNA_DSP_RATE_CTL_CHAN_MASK,
			      TACNA_RATE_ENUM_SIZE,
			      tacna_rate_text, tacna_rate_val),
};

static const struct snd_kcontrol_new clsic_dsp1_rx_rate_controls[] = {
	SOC_ENUM_EXT("DSP1RX1 Rate", clsic_dsp1_rx_rate_enum[0],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1RX2 Rate", clsic_dsp1_rx_rate_enum[1],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1RX3 Rate", clsic_dsp1_rx_rate_enum[2],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1RX4 Rate", clsic_dsp1_rx_rate_enum[3],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1RX5 Rate", clsic_dsp1_rx_rate_enum[4],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1RX6 Rate", clsic_dsp1_rx_rate_enum[5],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1RX7 Rate", clsic_dsp1_rx_rate_enum[6],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1RX8 Rate", clsic_dsp1_rx_rate_enum[7],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1RX9 Rate", clsic_dsp1_rx_rate_enum[8],
		     snd_soc_get_enum_double, tacna_rate_put),
};

static const struct snd_kcontrol_new clsic_dsp1_tx_rate_controls[] = {
	SOC_ENUM_EXT("DSP1TX1 Rate", clsic_dsp1_tx_rate_enum[0],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1TX2 Rate", clsic_dsp1_tx_rate_enum[1],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1TX3 Rate", clsic_dsp1_tx_rate_enum[2],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1TX4 Rate", clsic_dsp1_tx_rate_enum[3],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1TX5 Rate", clsic_dsp1_tx_rate_enum[4],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1TX6 Rate", clsic_dsp1_tx_rate_enum[5],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1TX7 Rate", clsic_dsp1_tx_rate_enum[6],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1TX8 Rate", clsic_dsp1_tx_rate_enum[7],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP1TX9 Rate", clsic_dsp1_tx_rate_enum[8],
		     snd_soc_get_enum_double, tacna_rate_put),
};

static const struct snd_kcontrol_new clsic_dsp2_rx_rate_controls[] = {
	SOC_ENUM_EXT("DSP2RX1 Rate", clsic_dsp2_rx_rate_enum[0],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2RX2 Rate", clsic_dsp2_rx_rate_enum[1],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2RX3 Rate", clsic_dsp2_rx_rate_enum[2],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2RX4 Rate", clsic_dsp2_rx_rate_enum[3],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2RX5 Rate", clsic_dsp2_rx_rate_enum[4],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2RX6 Rate", clsic_dsp2_rx_rate_enum[5],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2RX7 Rate", clsic_dsp2_rx_rate_enum[6],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2RX8 Rate", clsic_dsp2_rx_rate_enum[7],
		     snd_soc_get_enum_double, tacna_rate_put),
};

static const struct snd_kcontrol_new clsic_dsp2_tx_rate_controls[] = {
	SOC_ENUM_EXT("DSP2TX1 Rate", clsic_dsp2_tx_rate_enum[0],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2TX2 Rate", clsic_dsp2_tx_rate_enum[1],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2TX3 Rate", clsic_dsp2_tx_rate_enum[2],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2TX4 Rate", clsic_dsp2_tx_rate_enum[3],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2TX5 Rate", clsic_dsp2_tx_rate_enum[4],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2TX6 Rate", clsic_dsp2_tx_rate_enum[5],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2TX7 Rate", clsic_dsp2_tx_rate_enum[6],
		     snd_soc_get_enum_double, tacna_rate_put),
	SOC_ENUM_EXT("DSP2TX8 Rate", clsic_dsp2_tx_rate_enum[7],
		     snd_soc_get_enum_double, tacna_rate_put),
};

static const struct snd_kcontrol_new *clsic_dsp_rx_rate_controls[] = {
	clsic_dsp1_rx_rate_controls,
	clsic_dsp2_rx_rate_controls
};

static const struct snd_kcontrol_new *clsic_dsp_tx_rate_controls[] = {
	clsic_dsp1_tx_rate_controls,
	clsic_dsp2_tx_rate_controls
};

static void clsic_dsp_add_codec_controls(struct snd_soc_codec *codec,
					 unsigned int dsp_index,
					 unsigned int n_rx_channels,
					 unsigned int n_tx_channels)
{
	int ret;

	ret = snd_soc_add_codec_controls(codec,
					 clsic_dsp_rx_rate_controls[dsp_index],
					 n_rx_channels);
	if (ret)
		dev_err(codec->dev,
			"%s() ret:%d;Failed to add DSP%d rx rate ctls\n",
			__func__, ret, dsp_index + 1);

	ret = snd_soc_add_codec_controls(codec,
					 clsic_dsp_tx_rate_controls[dsp_index],
					 n_tx_channels);
	if (ret)
		dev_err(codec->dev,
			"%s() ret:%d;Failed to add DSP%d tx rate ctls\n",
			__func__, ret, dsp_index + 1);
};

static void clsic_dsps_add_codec_controls(struct clsic_codec *clsic_codec)
{
	struct snd_soc_codec *codec = clsic_codec->codec;
	int ret;

	/* Set DSP1 controls */
	clsic_dsp_add_codec_controls(codec, 0, CLSIC_DSP1_N_RX_CHANNELS,
						CLSIC_DSP1_N_TX_CHANNELS);

	/* Set DSP2 controls */
	if (clsic_codec->host_controls_dsp2) {
		ret = tacna_dsp_add_codec_controls(codec, CLSIC_NUM_DSP);
		if (ret)
			dev_err(codec->dev,
				"%s()ret:%d;Failed to add DSP rate ctls\n",
				__func__, ret);
	} else {
		clsic_dsp_add_codec_controls(codec, 1,
						CLSIC_DSP2_N_RX_CHANNELS,
						CLSIC_DSP2_N_TX_CHANNELS);
	}
};

static int clsic_codec_probe(struct snd_soc_codec *codec)
{
	struct clsic_codec *clsic_codec =
		snd_soc_codec_get_drvdata(codec);
	int ret;

	dev_info(codec->dev, "%s() %p\n", __func__, codec);

	clsic_codec->core.tacna->dapm = snd_soc_codec_get_dapm(codec);

	ret = tacna_init_inputs(codec);
	if (ret)
		return ret;

	clsic_codec->codec = codec;

	clsic_dsps_add_codec_controls(clsic_codec);

	if (clsic_codec->host_controls_dsp2) {
		ret = snd_soc_add_codec_controls(codec,
			clsic_snd_controls_dsp2_visible,
			ARRAY_SIZE(clsic_snd_controls_dsp2_visible));

		if (ret != 0)
			dev_err(codec->dev,
				"%s():%u Failed to add DSP2 controls: %d\n",
				__func__, __LINE__, ret);

		ret = snd_soc_dapm_new_controls(clsic_codec->core.tacna->dapm,
			clsic_dapm_widgets_dsp2_visible,
			ARRAY_SIZE(clsic_dapm_widgets_dsp2_visible));

		if (ret != 0)
			dev_err(codec->dev,
			       "%s():%u Failed to add DSP2 dapm controls: %d\n",
			       __func__, __LINE__, ret);

		ret = snd_soc_dapm_add_routes(clsic_codec->core.tacna->dapm,
			clsic_dapm_routes_dsp2_visible,
			ARRAY_SIZE(clsic_dapm_routes_dsp2_visible));

		if (ret != 0)
			dev_err(codec->dev,
				"%s():%u Failed to add DSP2 routes: %d\n",
				__func__, __LINE__, ret);

		wm_adsp2_codec_probe(&clsic_codec->core.dsp[1], codec);
	} else {
		ret = snd_soc_dapm_new_controls(clsic_codec->core.tacna->dapm,
			clsic_dapm_widgets_dsp2_hidden,
			ARRAY_SIZE(clsic_dapm_widgets_dsp2_hidden));

		if (ret != 0)
			dev_err(codec->dev,
			       "%s():%u Failed to add DSP2 dapm controls: %d\n",
			       __func__, __LINE__, ret);

		ret = snd_soc_dapm_add_routes(clsic_codec->core.tacna->dapm,
			clsic_dapm_routes_dsp2_hidden,
			ARRAY_SIZE(clsic_dapm_routes_dsp2_hidden));

		if (ret != 0)
			dev_err(codec->dev,
				"%s():%u Failed to add DSP2 routes: %d\n",
				__func__, __LINE__, ret);
	}

	return ret;
}

static int clsic_codec_remove(struct snd_soc_codec *codec)
{
	struct clsic_codec *clsic_codec =
		snd_soc_codec_get_drvdata(codec);
	struct tacna *tacna = clsic_codec->core.tacna;

	dev_info(codec->dev, "%s() %p\n", __func__, codec);

	tacna->dapm = NULL;

	if (clsic_codec->host_controls_dsp2)
		wm_adsp2_codec_remove(&clsic_codec->core.dsp[1], codec);

	return 0;
}

static const unsigned int clsic_digital_vu[] = {
	TACNA_IN1L_CONTROL2,
	TACNA_IN1R_CONTROL2,
	TACNA_IN2L_CONTROL2,
	TACNA_IN2R_CONTROL2,
	TACNA_IN3L_CONTROL2,
	TACNA_IN3R_CONTROL2,
	TACNA_IN4L_CONTROL2,
	TACNA_IN4R_CONTROL2,
};

static int clsic_set_fll(struct snd_soc_codec *codec, int fll_id, int source,
			 unsigned int fref, unsigned int fout)
{
	struct clsic_codec *clsic_codec = snd_soc_codec_get_drvdata(codec);
	int idx;

	switch (fll_id) {
	case TACNA_FLL1_REFCLK:
		idx = 0;
		break;
	case TACNA_FLL2_REFCLK:
		idx = 1;
		break;
	default:
		return -EINVAL;
	}

	return tacna_fllhj_set_refclk(&clsic_codec->fll[idx],
				      source, fref, fout);
}

static struct regmap *clsic_get_regmap(struct device *dev)
{
	struct clsic_codec *clsic_codec = dev_get_drvdata(dev);

	dev_dbg(dev, "%s() codec: %p regmap: %p\n", __func__,
		clsic_codec, clsic_codec->core.tacna->regmap);

	return clsic_codec->core.tacna->regmap;
}

static const struct snd_soc_codec_driver soc_codec_dev_clsic = {
	.probe = &clsic_codec_probe,
	.remove = &clsic_codec_remove,
	.get_regmap = &clsic_get_regmap,

	.idle_bias_off = true,

	.set_sysclk = &tacna_set_sysclk,
	.set_pll = &clsic_set_fll,

	.component_driver = {
		.controls = clsic_snd_controls,
		.num_controls = ARRAY_SIZE(clsic_snd_controls),
		.dapm_widgets = clsic_dapm_widgets,
		.num_dapm_widgets = ARRAY_SIZE(clsic_dapm_widgets),
		.dapm_routes = clsic_dapm_routes,
		.num_dapm_routes = ARRAY_SIZE(clsic_dapm_routes),
	},
};

static int clsic_probe(struct platform_device *pdev)
{
	struct tacna *tacna = dev_get_drvdata(pdev->dev.parent);
	struct clsic *clsic = dev_get_drvdata(tacna->dev->parent);
	struct clsic_codec *clsic_codec;
	struct wm_adsp *dsp;
	int i, ret;

	BUILD_BUG_ON(ARRAY_SIZE(clsic_dai) > TACNA_MAX_DAI);

	clsic_codec = devm_kzalloc(&pdev->dev,
				   sizeof(struct clsic_codec),
				   GFP_KERNEL);
	if (clsic_codec == NULL)
		return -ENOMEM;

	platform_set_drvdata(pdev, clsic_codec);

	/* share of_node with the clsic device */
	pdev->dev.of_node = of_node_get(clsic->dev->of_node);

	clsic_codec->clsic = clsic;

	clsic_codec->host_controls_dsp2 = of_property_read_bool(
							clsic->dev->of_node,
							"host_controls_dsp2");

	clsic_codec->core.tacna = tacna;
	clsic_codec->core.dev = &pdev->dev;
	clsic_codec->core.num_inputs = 8;
	clsic_codec->core.max_analogue_inputs = 0;
	clsic_codec->core.num_dmic_clksrc = 4;

	ret = tacna_core_init(&clsic_codec->core);
	if (ret)
		return ret;

	clsic_micbias_init(clsic_codec);

	/* TODO: initialise dsp2 MPU error interrupt */
	dsp = &clsic_codec->core.dsp[1];
	dsp->num = 2;
	dsp->dev = clsic_codec->core.tacna->dev;

	if (clsic_codec->host_controls_dsp2) {
		dsp->part = clsic_devid_to_string(clsic->devid);
		dsp->type = WMFW_HALO;
		dsp->rev = 0;
		dsp->regmap = clsic_codec->core.tacna->dsp_regmap[1];
		dsp->base = TACNA_DSP2_CLOCK_FREQ;
		dsp->base_sysinfo = TACNA_DSP2_SYS_INFO_ID;
		dsp->mem = clsic_dsp2_regions;
		dsp->num_mems = ARRAY_SIZE(clsic_dsp2_regions);
	}

	dsp->n_rx_channels = CLSIC_DSP2_N_RX_CHANNELS;
	dsp->n_tx_channels = CLSIC_DSP2_N_TX_CHANNELS;

	ret = wm_halo_init(dsp, &clsic_codec->core.rate_lock);
	if (ret != 0)
		dev_err(&pdev->dev, "Failed to initialise DSP2.\n");

	for (i = 0 ; i < CLSIC_N_FLL ; ++i) {
		clsic_codec->fll[i].tacna_priv = &clsic_codec->core;
		clsic_codec->fll[i].id = i + 1;
		clsic_codec->fll[i].base = TACNA_FLL1_CONTROL1 + i * 0x100;
		clsic_codec->fll[i].sts_addr = CLSIC_IRQ2_STS6;
		clsic_codec->fll[i].sts_mask =
			CLSIC_FLL1_LOCK_STS2_MASK << (2 * i);
		tacna_init_fll(&clsic_codec->fll[i]);
	}

	for (i = 0; i < ARRAY_SIZE(clsic_dai); i++)
		tacna_init_dai(&clsic_codec->core, i);

	/* Latch volume update bits */
	for (i = 0; i < ARRAY_SIZE(clsic_digital_vu); i++)
		regmap_update_bits(clsic_codec->core.tacna->regmap,
				   clsic_digital_vu[i],
				   TACNA_IN_VU_MASK, TACNA_IN_VU);

	pm_runtime_enable(&pdev->dev);
	pm_runtime_idle(&pdev->dev);

	ret = snd_soc_register_codec(&pdev->dev, &soc_codec_dev_clsic,
				     clsic_dai, ARRAY_SIZE(clsic_dai));
	if (ret < 0) {
		dev_err(&pdev->dev, "Failed to register codec: %d\n", ret);
		snd_soc_unregister_platform(&pdev->dev);
	}

	dev_info(&pdev->dev, "%s() dev %p ret %d\n", __func__, &pdev->dev, ret);

	return ret;
}

static int clsic_remove(struct platform_device *pdev)
{
	struct clsic_codec *clsic_codec = platform_get_drvdata(pdev);
	struct tacna *tacna = dev_get_drvdata(pdev->dev.parent);
	struct clsic *clsic = dev_get_drvdata(tacna->dev->parent);

	dev_dbg(&pdev->dev, "%s() dev %p clsic %p priv %p\n",
		__func__, &pdev->dev, clsic, clsic_codec);

	/* TODO XXX The stashed regmap is not valid from this point on */

	snd_soc_unregister_codec(&pdev->dev);
	pm_runtime_disable(&pdev->dev);

	if (clsic_codec->host_controls_dsp2)
		wm_adsp2_remove(&clsic_codec->core.dsp[1]);

	tacna_core_destroy(&clsic_codec->core);

	return 0;
}

static struct platform_driver clsic_codec_driver = {
	.driver = {
		.name = "clsic-codec",
		.owner = THIS_MODULE,
	},
	.probe = &clsic_probe,
	.remove = &clsic_remove,
};

module_platform_driver(clsic_codec_driver);

MODULE_DESCRIPTION("ASoC Cirrus Logic CLSIC codec");
MODULE_AUTHOR("Simon Trimmer <simont@opensource.cirrus.com>");
MODULE_AUTHOR("Piotr Stankiewicz <piotrs@opensource.wolfsonmicro.com>");
MODULE_LICENSE("GPL v2");
MODULE_ALIAS("platform:clsic-codec");
