/*
 * Interrupt support for Cirrus Logic Tacna codecs
 *
 * Copyright 2017 Cirrus Logic, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef IRQCHIP_TACNA_H
#define IRQCHIP_TACNA_H

/* Main interrupts, organized by priority order - highest first */
#define TACNA_IRQ_OUT1R_SC			0
#define TACNA_IRQ_OUT1L_SC			1
#define TACNA_IRQ_OUT2R_SC			2
#define TACNA_IRQ_OUT2L_SC			3
#define TACNA_IRQ_OUT3R_SC			4
#define TACNA_IRQ_OUT3L_SC			5
#define TACNA_IRQ_OUT4R_SC			6
#define TACNA_IRQ_OUT4L_SC			7
#define TACNA_IRQ_DSP1_IRQ0			8
#define TACNA_IRQ_DSP2_IRQ0			9
#define TACNA_IRQ_DSP3_IRQ0			10
#define TACNA_IRQ_DSP4_IRQ0			11
#define TACNA_IRQ_DSP1_IRQ1			12
#define TACNA_IRQ_DSP2_IRQ1			13
#define TACNA_IRQ_DSP3_IRQ1			14
#define TACNA_IRQ_DSP4_IRQ1			15
#define TACNA_IRQ_DSP1_IRQ2			16
#define TACNA_IRQ_DSP2_IRQ2			17
#define TACNA_IRQ_DSP3_IRQ2			18
#define TACNA_IRQ_DSP4_IRQ2			19
#define TACNA_IRQ_DSP1_IRQ3			20
#define TACNA_IRQ_DSP2_IRQ3			21
#define TACNA_IRQ_DSP3_IRQ3			22
#define TACNA_IRQ_DSP4_IRQ3			23
#define TACNA_IRQ_US1_ACT_DET_RISE		24
#define TACNA_IRQ_US1_ACT_DET_FALL		25
#define TACNA_IRQ_US2_ACT_DET_RISE		26
#define TACNA_IRQ_US2_ACT_DET_FALL		27
#define TACNA_IRQ_US3_ACT_DET_RISE		28
#define TACNA_IRQ_US3_ACT_DET_FALL		29
#define TACNA_IRQ_INPUTS_SIG_DET_RISE		30
#define TACNA_IRQ_INPUTS_SIG_DET_FALL		31
#define TACNA_IRQ_INPUTS_SIG_DET_AO_RISE	32
#define TACNA_IRQ_INPUTS_SIG_DET_AO_FALL	33
#define TACNA_IRQ_HPDET				34
#define TACNA_IRQ_MICDET1			35
#define TACNA_IRQ_MICDET2			36
#define TACNA_IRQ_GPIO1_RISE			37
#define TACNA_IRQ_GPIO1_FALL			38
#define TACNA_IRQ_GPIO2_RISE			39
#define TACNA_IRQ_GPIO2_FALL			40
#define TACNA_IRQ_GPIO3_RISE			41
#define TACNA_IRQ_GPIO3_FALL			42
#define TACNA_IRQ_GPIO4_RISE			43
#define TACNA_IRQ_GPIO4_FALL			44
#define TACNA_IRQ_GPIO5_RISE			45
#define TACNA_IRQ_GPIO5_FALL			46
#define TACNA_IRQ_GPIO6_RISE			47
#define TACNA_IRQ_GPIO6_FALL			48
#define TACNA_IRQ_GPIO7_RISE			49
#define TACNA_IRQ_GPIO7_FALL			50
#define TACNA_IRQ_GPIO8_RISE			51
#define TACNA_IRQ_GPIO8_FALL			52
#define TACNA_IRQ_OUT1R_ENABLE_DONE		53
#define TACNA_IRQ_OUT1L_ENABLE_DONE		54
#define TACNA_IRQ_OUT2R_ENABLE_DONE		55
#define TACNA_IRQ_OUT2L_ENABLE_DONE		56
#define TACNA_IRQ_OUT3R_ENABLE_DONE		57
#define TACNA_IRQ_OUT3L_ENABLE_DONE		58
#define TACNA_IRQ_OUT4R_ENABLE_DONE		59
#define TACNA_IRQ_OUT4L_ENABLE_DONE		60
#define TACNA_IRQ_OUT1R_DISABLE_DONE		61
#define TACNA_IRQ_OUT1L_DISABLE_DONE		62
#define TACNA_IRQ_OUT2R_DISABLE_DONE		63
#define TACNA_IRQ_OUT2L_DISABLE_DONE		64
#define TACNA_IRQ_OUT3R_DISABLE_DONE		65
#define TACNA_IRQ_OUT3L_DISABLE_DONE		66
#define TACNA_IRQ_OUT4R_DISABLE_DONE		67
#define TACNA_IRQ_OUT4L_DISABLE_DONE		68
#define TACNA_IRQ_OUTH_ENABLE_DONE		69
#define TACNA_IRQ_OUTH_DISABLE_DONE		70
#define TACNA_IRQ_DRC1_SIG_DET_RISE		71
#define TACNA_IRQ_DRC1_SIG_DET_FALL		72
#define TACNA_IRQ_DRC2_SIG_DET_RISE		73
#define TACNA_IRQ_DRC2_SIG_DET_FALL		74
#define TACNA_IRQ_JD2_HDRV_RISE			75
#define TACNA_IRQ_JD2_HDRV_FALL			76
#define TACNA_IRQ_FLL1_LOCK_RISE		77
#define TACNA_IRQ_FLL1_LOCK_FALL		78
#define TACNA_IRQ_FLL2_LOCK_RISE		79
#define TACNA_IRQ_FLL2_LOCK_FALL		80
#define TACNA_IRQ_FLL3_LOCK_RISE		81
#define TACNA_IRQ_FLL3_LOCK_FALL		82
#define TACNA_IRQ_FLL1_REF_LOST			83
#define TACNA_IRQ_FLL2_REF_LOST			84
#define TACNA_IRQ_FLL3_REF_LOST			85
#define TACNA_IRQ_FLL1AO_RELOCK_FAIL		86
#define TACNA_IRQ_SYSCLK_FAIL			87
#define TACNA_IRQ_CTRLIF_ERR			88
#define TACNA_IRQ_SYSCLK_ERR			89
#define TACNA_IRQ_ASYNCCLK_ERR			90
#define TACNA_IRQ_DSPCLK_ERR			91
#define TACNA_IRQ_AOCLK_ERR			92
#define TACNA_IRQ_DSP1_NMI			93
#define TACNA_IRQ_DSP1_WDT_EXPIRE		94
#define TACNA_IRQ_DSP1_MPU_ERR			95
#define TACNA_IRQ_DSP2_NMI			96
#define TACNA_IRQ_DSP2_WDT_EXPIRE		97
#define TACNA_IRQ_DSP2_MPU_ERR			98
#define TACNA_IRQ_DSP3_NMI			99
#define TACNA_IRQ_DSP3_WDT_EXPIRE		100
#define TACNA_IRQ_DSP3_MPU_ERR			101
#define TACNA_IRQ_DSP4_NMI			102
#define TACNA_IRQ_DSP4_WDT_EXPIRE		103
#define TACNA_IRQ_DSP4_MPU_ERR			104
#define TACNA_IRQ_MCU_HWERR			105
#define TACNA_IRQ_BOOT_DONE			106
#define TACNA_IRQ_ASRC1_IN1_LOCK_RISE		107
#define TACNA_IRQ_ASRC1_IN1_LOCK_FALL		108
#define TACNA_IRQ_ASRC1_IN2_LOCK_RISE		109
#define TACNA_IRQ_ASRC1_IN2_LOCK_FALL		110
#define TACNA_IRQ_ASRC2_IN1_LOCK_RISE		111
#define TACNA_IRQ_ASRC2_IN1_LOCK_FALL		112
#define TACNA_IRQ_ASRC2_IN2_LOCK_RISE		113
#define TACNA_IRQ_ASRC2_IN2_LOCK_FALL		114
#define TACNA_IRQ_SECURE_MODE_RISE		115
#define TACNA_IRQ_SECURE_MODE_FALL		116

#define TACNA_NUM_MAIN_IRQ			117

/* AOD interrupts */
#define TACNA_IRQ_AOD_JD1_RISE		(TACNA_NUM_MAIN_IRQ + 0)
#define TACNA_IRQ_AOD_JD1_FALL		(TACNA_NUM_MAIN_IRQ + 1)
#define TACNA_IRQ_AOD_JD2_RISE		(TACNA_NUM_MAIN_IRQ + 2)
#define TACNA_IRQ_AOD_JD2_FALL		(TACNA_NUM_MAIN_IRQ + 3)
#define TACNA_IRQ_AOD_MICD_CLAMP1_RISE	(TACNA_NUM_MAIN_IRQ + 4)
#define TACNA_IRQ_AOD_MICD_CLAMP1_FALL	(TACNA_NUM_MAIN_IRQ + 5)
#define TACNA_IRQ_AOD_JD3_RISE		(TACNA_NUM_MAIN_IRQ + 6)
#define TACNA_IRQ_AOD_JD3_FALL		(TACNA_NUM_MAIN_IRQ + 7)
#define TACNA_IRQ_AOD_MICD_CLAMP2_RISE	(TACNA_NUM_MAIN_IRQ + 8)
#define TACNA_IRQ_AOD_MICD_CLAMP2_FALL	(TACNA_NUM_MAIN_IRQ + 9)

#define TACNA_NUM_AOD_IRQ		10
#define TACNA_NUM_IRQ (TACNA_NUM_MAIN_IRQ + TACNA_NUM_AOD_IRQ)

struct tacna;

int tacna_request_irq(struct tacna *tacna, int irq, const char *name,
		      irq_handler_t handler, void *data);
void tacna_free_irq(struct tacna *tacna, int irq, void *data);
int tacna_set_irq_wake(struct tacna *tacna, int irq, int on);

#endif
